### ISSUE TITLE
Consider Automatically Calling State.RemoveResource() After Successful Resource Deletion

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-framework#100]
### Module version

```
v0.2.0
```

### Use-cases

Currently the framework requires all resource implementations to include this type of logic in the `Delete()` method:

```go
func (r exampleResource) Delete(ctx context.Context, req tfsdk.DeleteResourceRequest, resp *tfsdk.DeleteResourceResponse) {
	// logic to delete resource

	resp.State.RemoveResource(ctx)
}
```

Is there ever a time this would not be desired on successful deletion? Maybe we can save a few keystrokes.

### Proposal

Implement `State.RemoveResource(ctx)` in the calling code on `Delete()` success so it is not necessary for all implementations. From the previous framework:

https://github.com/hashicorp/terraform-plugin-sdk/blob/c455248338544ae42b6449eae44279c0c82d7987/helper/schema/resource.go#L428-L434

**Comment by bflad** [comment]
Thinking further, if for some reason the behavior wasn't desired (such as certain warning-only situations maybe?), we could implement an additional field in the response, e.g.

```go
KeepResourceState bool
```

**Comment by paddycarver** [comment]
My only hesitation, personally, is that this was always (in my experience) surprising behavior in SDKv2. People had no idea this would happen, and so kept removing things from state manually. I don't know that that disqualifies it, but it gives me pause, at least.

**Comment by bflad** [comment]
I think we'd much rather have folks potentially doing it unnecessarily, rather than not at all though, right?

**Comment by paddycarver** [comment]
I'm not sure I would. I think not doing it at all would be caught during acceptance testing, or should be caught during acceptance testing. And then at least people would be sure about what the code was doing. Doing it unnecessarily smells to me like people not knowing what their responsibilities in the framework are, and I think clear expectations are better than We Know What You Meant.

I don't know that I'm strictly against the idea, or that the convenience tradeoff of having it done automatically isn't worth the clarity tradeoff of not knowing if you need to do it or not. But I do feel like there's a tradeoff at play here and that Just Doing The Right Thing isn't free.
