### ISSUE TITLE
tfsdk support embeded struct

### ISSUE THREAD

**Issue by LuoYuWuSheng** [hashicorp/terraform-plugin-framework#1024]
### Module version

```
...
```

### Use-cases

can `tfsdk` support embeded struct ? just lik gorm https://gorm.io/docs/models.html#embedded_struct

**Comment by SBGoods** [comment]
Hi @LuoYuWuSheng 👋🏾,
Thank you for opening this issue. Last week, we merged #1021 adding embedded struct support which will be included in this week's `terraform-plugin-framework v1.11.0` release. I will be closing this issue as resolved for now, but please feel free to open another issue after the `v1.11.0` release if you find any issues with the embedded struct support.
