### ISSUE TITLE
Document validation

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#103]
With the merging of validation (#82, #75) we now have functionality that's not documented on terraform.io again. We should add a page for validation, and update our section on custom types, to document how to validate things.

**Comment by bflad** [comment]
Just ensuring this is captured: there have been multiple asks around unknown attribute value handling -- the current implementation always calls validation and allows implementors to choose on the desired logic on unknown values, but this could be confusing at first. e.g. this type of logic will likely be common:

```go
value, ok := req.AttributeConfig.(types.String)

if !ok {
	return
}

if value.Unknown {
	return
}
```

So we should ensure that is well documented to consider this value state to prevent potential frustration. Higher level abstractions may be able to choose the more common path of ignoring unknown values.

**Comment by paddycarver** [comment]
I think this is superseded by #144.
