### ISSUE TITLE
SingleNestedAttributes validation failure if the attribute is not present in configuration

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-framework#112]
Relates #17.
With the latest (fad6afe33058c5a2581d1e424a50c7fc9a842ff3) code, suppose I have a schema like this:

```go
tfsdk.Schema{
	Attributes:  map[string]tfsdk.Attribute{
		"name": {
			Type:        types.StringType,
			Optional:    true,
		},

		"blah_configuration": {
			Attributes: tfsdk.SingleNestedAttributes(
				map[string]tfsdk.Attribute{
					"insights_enabled": {
						Type:        types.BoolType,
						Optional:    true,
					},
					"notifications_enabled": {
						Type:        types.BoolType,
						Optional:    true,
					},
				},
			),
			Optional: true,
		},
	},
}
```

and a configuration like this (`blah_configuration` not specified):

```hcl
resource "blah" "test" {
  name = "testing"
}
```

`terraform plan` errors:

```console
% terraform plan
╷
│ Error: Configuration Read Error
│ 
│   with blah.test,
│   on main.tf line 46, in resource "blah" "test":
│   46: resource "blah" "test" {
│ 
│ An unexpected error was encountered trying to read an attribute from the configuration. This is always an error in the provider. Please report the following to the
│ provider developer:
│ 
│ AttributeName("insights_enabled") still remains in the path: step cannot be applied to this value
╵
╷
│ Error: Configuration Read Error
│ 
│   with blah.test,
│   on main.tf line 46, in resource "blah" "test":
│   46: resource "blah" "test" {
│ 
│ An unexpected error was encountered trying to read an attribute from the configuration. This is always an error in the provider. Please report the following to the
│ provider developer:
│ 
│ AttributeName("notifications_enabled") still remains in the path: step cannot be applied to this value
╵
```

**Comment by ewbankkit** [comment]
I have tracked this down to the validation of the `SingleNestedAttribute` (which is Null).
I can work around this by adding

```go
			o, ok := req.AttributeConfig.(types.Object)

			if !ok {
				err := fmt.Errorf("unknown attribute value type (%T) for nesting mode (%T) at path: %s", req.AttributeConfig, nm, req.AttributePath)
				resp.Diagnostics = append(resp.Diagnostics, &tfprotov6.Diagnostic{
					Severity:  tfprotov6.DiagnosticSeverityError,
					Summary:   "Attribute Validation Error",
					Detail:    "Attribute validation cannot walk schema. Report this to the provider developer:\n\n" + err.Error(),
					Attribute: req.AttributePath,
				})

				return
			}

			if len(o.Attrs) > 0 {
				// Existing code...
			}
```

here

https://github.com/hashicorp/terraform-plugin-framework/blob/fad6afe33058c5a2581d1e424a50c7fc9a842ff3/tfsdk/attribute.go#L322

**Comment by tckb** [comment]
@ewbankkit dp you have any workaround for this? currently I'm using `ListNestedAttributesOptions` as a replacement

**Comment by ewbankkit** [comment]
I have a fork - https://github.com/ewbankkit/terraform-plugin-framework/commits/f-allow-nested-attributes-instantiation - that works around this.

**Comment by kmoe** [comment]
The error is thrown by this line: https://github.com/hashicorp/terraform-plugin-framework/blob/fad6afe33058c5a2581d1e424a50c7fc9a842ff3/tfsdk/config.go#L80

`tftypes.WalkAttributePath()` errors because it's trying to find the value `AttributeName("insights_enabled")` is pointing to, in a nil object. 

We could change the terraform-plugin-go behaviour here and have it return nil in such cases, but I think in this case the semantics would be incorrect (in contrast to https://github.com/hashicorp/terraform-plugin-framework/commit/fad6afe33058c5a2581d1e424a50c7fc9a842ff3, which I believe reflects user intuitions for our higher-level state abstraction on top of tftypes).

Kit's fix is therefore correct. @ewbankkit, could you raise a PR from your fork?
