### ISSUE TITLE
Consider InternalValidate equivalent

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-framework#113]
The `Provider.InternalValidate()` and `Resource.InternalValidate()` (which calls `schemaMap.InternalValidate()`, `Importer.InternalValidate()`) exported functions in `terraform-plugin-sdk` provide a way for callers to validate that, for example:

 - `Optional` and `Required` cannot both be set on the same attribute
 - If a resource has no `Update`, all `Computed` attributes must be `ForceNew`
 - State upgraders must cover all appropriate schema versions
 - Context-aware CRUD functions and their non-context-aware equivalents cannot both be set

While many of these do not apply to `terraform-plugin-framework`, we should consider whether an equivalent function is appropriate.

The `InternalValidate` equivalent(s) could validate that:
 - `PlanModifiers` are not set on data sources (see #102)

Alternatively, we can declare a user-run internal validation function an anti-pattern, in which case this issue should be closed and the above validation done through other means.

**Comment by bflad** [comment]
https://github.com/hashicorp/terraform-plugin-framework/issues/157 has an example use case that this theoretical functionality could also check that configuration validation fields are not defined on schemas with no configurable attributes.

**Comment by bflad** [comment]
At this juncture, I'm inclined to recommend that we implement any remaining validations to get returned as error diagnostics as part of the `GetProviderSchema` response. This will ensure that the provider will not work appropriately in acceptance testing and production, should there be correctness issues. For stylistic issues or coding recommendations, external tooling can be created.
