### ISSUE TITLE
Better string representation of `terraform-plugin-framework/types` values

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-framework#117]
For logging and debugging purposes a better representation of `terraform-plugin-framework/types` values would help.
For example, currently `fmt.Printf("%s")` of a `types.Number` with value `6.5` displays:

```
{%!s(bool=false) %!s(bool=false) %!s(*big.Float=6.5)}
```

**Comment by paddycarver** [comment]
I think I'd like to duplicate what `tftypes.Value` has, but it may be worth 🤔 about how exactly to do that, since technically each `attr.Value` gets to control its `String` implementation.
