### ISSUE TITLE
Consider Splitting tfsdk.Attribute into datasource.Attribute, provider.Attribute, and resource.Attribute

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-framework#132]
### Module version

Post plan modification support

### Use-cases

Plan modifications can only occur on resource attributes. Since the `Attribute` type is shared across data source, provider, and resource schemas, it is possible to define plan modifiers on data source and provider attributes which will have no effect. This can be confusing for provider developers.

### Attempted Solutions

Note behavior in Go documentation.

### Proposal

Consider creating separate Go types for data source, provider, and resource attributes which can cause compile-time errors for functionality not supported by each type. e.g.

```go
package datasource
type Attribute struct{
  // ... Type, etc. ....
}

package provider
type Attribute struct{
  // ... Type, etc. ....
}

package resource
type Attribute struct{
  // ... Type, etc. ....
  PlanModifiers []AttributePlanModifier
}
```

### References

- https://github.com/hashicorp/terraform-plugin-framework/pull/123/files#r702095995

**Comment by paddycarver** [comment]
I am gently suspicious that the fix will make things confusing (nested attributes can accept provider attributes inside a data source attribute?) but I think it's an interesting line of inquiry.
