### ISSUE TITLE
Update supporting materials for v0.3.0

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#138]
### Module version

```
v0.3.0
```

Now that v0.3.0 is out, with a bunch of new features and breaking changes in tow, we should update our supporting materials to keep them current:

**Must do (make info correct):**

* [x] #139
* [x] #140
* [x] #141
* [x] #142

**Stretch goals:**

* [ ] #143
* [ ] #144
* [ ] #145
* [x] #146

**Comment by bflad** [comment]
Stretch goals can be tracked in #143, #144, #145
