### ISSUE TITLE
Update https://learn.hashicorp.com/tutorials/terraform/plugin-framework-create to not use type assertions at all

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#146]

**Comment by bflad** [comment]
I took a look through the following:

- https://github.com/hashicorp/terraform-provider-hashicups-pf/tree/main/hashicups
- https://github.com/hashicorp/learn/blob/master/content/tutorials/terraform/plugin-framework-create.mdx

And did not find any type assertions (minus the `NewDataSource()` and `NewResource()` implementations, which are expected). 👍
