### ISSUE TITLE
Figure out how to minimize impact of practitioners going from blocks to attributes

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#159]
When providers upgrade from blocks to nested attributes practitioners are going to have an avalanche of breaking changes, places they need to insert an `=` into their configs to get them working again.

If we don't do something to mitigate that, it may be too large a pill to ask provider developers to swallow. We should see what we can do about making that upgrade requirement more palatable.

**Comment by vravind1** [comment]
there is no planned work in the next quarter
