### ISSUE TITLE
Add plan modification support to `attr.Type`

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#161]
### Module version

```
main@b0e3081ddbdab74c40ed0def9b8c23816a93d8fe
```

### Use-cases

Several types have semantically equivalent representations that are not byte-for-byte equivalent like Terraform requires. A JSON type comes to mind, in which

```json
{
  "key": "value"
}
```

and

```json
{"key": "value"}
```

should be considered equal, but Terraform treats as distinct values. By allowing plan modification strategies to be associated with `attr.Type`s, we can make sure this behavior is applied consistently everywhere the type is used.

### Attempted Solutions

We can work around this by adding an `AttributePlanModifier` to each `schema.Attribute`, but that requires consistency and extra work for provider developers that can be avoided.

### Proposal

Similar to [`attr.TypeWithValidate`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/attr#TypeWithValidate) we create an `attr.TypeWithModifyPlan` that allows defining plan modification for the type. This plan modification runs before attribute plan modification and before whole resource plan modification.

**Comment by bflad** [comment]
(Old) example implementation for reference: https://github.com/hashicorp/terraform-plugin-framework/pull/162

**Comment by bflad** [comment]
This is covered by #737 👍
