### ISSUE TITLE
Consider making `attr.Value.ToTerraformValue` return a `tftypes.Value`

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#171]
It's honestly pretty bizarre that [`attr.Value.ToTerraformValue`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/attr#Value.ToTerraformValue) wants type developers to return an `interface{}` that needs to be one of the types accepted by [`tftypes.NewValue`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-go/tftypes#NewValue). It means that nothing ever happens with those values except calling `tftypes.NewValue` and including them, which just makes code dealing with that unnecessarily verbose. It also introduces a weird, murky integration point that seems at odds with the rest of the framework in that it doesn't really take advantage of any compile-time checks that what you're doing is valid and there's no real reason it can't.

I think the reason I originally pitched it like that was because `attr.Type` was returning the `tftypes.Type`, and so rather than making the type developer specify the `tftypes.Type` in both places, I figured the framework could just do it, because it already had that information. But that's not really a good enough justification for how bizarre that integration point is.

I think we should probably consider just asking for a `tftypes.Value` from that method, instead.

**Comment by bflad** [comment]
I'm a big 👍  on this given the current state of affairs and other design preferences of the framework. I'm also guessing that depending on the implementation of https://github.com/hashicorp/terraform-plugin-framework/issues/172, this might become less of an issue in some regards (instead working with `attr.Value` in many more places).
