### ISSUE TITLE
Reexamine where we convert from Terraform values into `attr.Value`s.

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#172]
Currently, the framework is following a model of keeping everything as a `tftypes.Value` all the way through the framework, until the config, state, or plan tries to retrieve it, then converts back from an `attr.Value` into a `tftypes.Value` when setting the config, state, or plan. That means that for all the framework code, we're more likely to be using the `tftypes.Value` abstraction than the `attr.Value` abstraction provider developers are using and expect.

I'm suspicious that we can clean up a lot of code, handle a lot of edge cases, and make more things work intuitively the way provider developers expect if we instead convert from `tftypes.Value`s into `attr.Value`s when handling protocol requests, and then passing around the `attr.Value`s.

**Comment by bflad** [comment]
I think this pairs well with https://github.com/hashicorp/terraform-plugin-framework/issues/215 👍

**Comment by bflad** [comment]
Created bespoke issues for tracking specific pieces of framework updates:

- #588 
- #589 
- #590

If there are other places which need updates, we can create other new issues.
