### ISSUE TITLE
Strange behavior with `Computed` attributes after v0.4.2 upgrade

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-framework#187]
I upgraded to `terraform-plugin-framework@v0.4.2` and am now seeing some strange behavior.
A resource has an attribute

```go
"function_name": {
	Description: "The name of the Lambda function, up to 64 characters in length. If you don't specify a name, AWS CloudFormation generates one.",
	Type:        types.StringType,
	Optional:    true,
	Computed:    true,
	Validators: []tfsdk.AttributeValidator{
		validate.StringLenAtLeast(1),
	},
	PlanModifiers: []tfsdk.AttributePlanModifier{
		tfsdk.RequiresReplace(),
	},
},
```

When `terraform plan` shows a difference in another attribute (`description` in this case which is _Optional_ and is now getting a value):

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # cloud_service_thing.test must be replaced
-/+ resource "cloud_service_thing" "test" {
      ~ arn                 = "..." -> (known after apply)
      + description         = "test"
      ~ function_name       = "1WlhknThPCtZOiZjwt283Olmq-0A8jrKEtMBpJ" -> (known after apply) # forces replacement
      ~ id                  = "1WlhknThPCtZOiZjwt283Olmq-0A8jrKEtMBpJ" -> (known after apply)
        # (9 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

The attribute `function_name` (which hasn't changed) is showing a change (and a replacement as it's _ForceNew_).
`arn` and `id` are also both _Computed_ attributes and their values have not changed.
This behavior was not observed with `v0.4.0`.

**Comment by bflad** [comment]
This behavior is (unfortunately) expected with the current implementation of `RequiresReplace()`, which will unilaterally mark an attribute for replacement any time there is _any_ plan difference, even outside the scope of the current attribute.

As shown in hashicorp/terraform-provider-awscc#222 this behavior can be improved with the following workaround:

```go
tfsdk.RequiresReplaceIf(func(ctx context.Context, state, config attr.Value, path *tftypes.AttributePath) (bool, diag.Diagnostics) {
	// TODO: Use config.IsNull() when available
	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/193
	if config.Equal(state) || config.Equal(types.String{Null: true}) {
		return false, nil
	}

	return true, nil
}, "require replacement if configuration value changes", "require replacement if configuration value changes"),
```

Whether either or both parts of the conditional there should be part of the `RequiresReplace()` implementation is an interesting design consideration. I would posit that most folks would expect it to work similarly to `ForceNew` in the older Terraform Plugin SDK, which only marked the path for replacement when configuration values changed.
