### ISSUE TITLE
Build up integration test framework

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#19]
### Module version

```
N/A
```

### Use-cases

Similar to how the Terraform CLI has a built-in provider that they can integration test with, we should build a simple provider in an internal package that we can puppet with Terraform to ensure that all the pieces hook up the way we think they do. This could, alternatively, be [the corner provider](https://github.com/hashicorp/terraform-provider-corner), but we need to make that seamless so we can get test failures for that reported on PRs in this repository and it's simple and straightforward to contribute new tests when adding functionality or fixing bugs in the framework. The goal here is for us to have very, very good test coverage, and the best way to do that is to make adding tests easy.

**Comment by tckb** [comment]
@paddycarver  I understand this is still open. I was wondering if there's any other way to start testing the provider implementation. I am mostly interested in the integration/acceptance tests.

**Comment by bflad** [comment]
Hi @tckb 👋  Just for some context, I believe this issue is intended to build a suite of integration testing for the framework code itself, beyond the existing unit testing.

For provider developers and until if/when a newer testing framework is developed, you should be able to use the [previous framework's acceptance testing framework](https://www.terraform.io/docs/extend/testing/index.html), utilizing the protocol 6 support from [`helper/resource.TestCase.ProtoV6ProviderFactories](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#TestCase.ProtoV6ProviderFactories). It may not necessarily be able to handle all the newer framework's concepts for state value checking, such as nested attributes, but it should be able to verify at least a subset of provider functionality.

**Comment by paddycarver** [comment]
There's some more prescriptive guidance on how to do that here, too: https://www.terraform.io/docs/plugin/framework/acctests.html

**Comment by tckb** [comment]
ah! I miss understood.  thanks @bflad  yes I already went through the current sdkv2 acctesting framework. It looks pretty good and I was trying to see if this is possible at the moment.  When the new framework is developed, it should be in this repository `terraform-plugin-framework`  correct?

**Comment by paddycarver** [comment]
I think that remains an open question, whether it will be a plugin-framework-specific test framework that lives in this repository, a test framework that plugin-sdk, plugin-go, and plugin-framework can _all_ use, which would likely live in its own repository, I think. We're currently weighing the pros and cons of those options.

**Comment by kmoe** [comment]
I think the best solution for this is to keep building up test cases with framework-implemented resources in terraform-provider-corner, and add a CI job for framework PRs that:
 - pulls the main branch of terraform-provider-corner
 - adds a `replace` directive to the provider's `go.mod` that points to the code on the current branch
 - runs the subset of terraform-provider-corner tests that concern resources implemented in the framework (we can name them `TestAccFramework`... etc)

This will be seamless once we've set it up, and avoid duplicating work.

**Comment by paddycarver** [comment]
I believe I am largely in agreement with that approach. 🤔

**Comment by bflad** [comment]
That sounds good to me. 👍

**Comment by tckb** [comment]
thanks @paddycarver  -  I;ve been adopting the framework since few releases, currently I am a made up framework for testing my provider. It would be a great help if there are some recomended approaches for writing the acceptance testing, given there is no framework available.

**Comment by paddycarver** [comment]
Hey @tckb, [terraform.io](https://www.terraform.io/docs/plugin/framework/acctests.html) has a page about our recommended approach to testing framework providers at the moment.

**Comment by kmoe** [comment]
The approach described in https://github.com/hashicorp/terraform-plugin-framework/issues/19#issuecomment-924838048 is implemented in #192 and documented in https://github.com/hashicorp/terraform-plugin-framework/pull/199.

@paddycarver and @bflad, is there anything else you'd like to see on the integration testing front?

**Comment by paddycarver** [comment]
I think our next step is to identify the integration tests we want to write (looking through `serve_test.go` may be useful in this regard) and creating an issue for them, transforming this into an epic.

I would also love to see the chicken and egg issue described resolved, and it feels like having a way to modify the `go.mod` of the integration test CI check that #192 added would be a reasonable solution to this. I don't fully know how we'd go about doing that, though, and what the security implications of it are 🤔
