### ISSUE TITLE
attr: Consider Adding IsNull() and IsUnknown() methods to Value

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-framework#193]
### Module version

```
v0.4.2
```

### Use-cases

When writing attribute plan modifiers, it can be necessary to check if the configuration or state `attr.Value` are null or unknown. It feels a little tedious to have to know the underlying value type for comparison and how to properly create the conditional.

### Attempted Solutions

```go
"function_name": {
			// Property: FunctionName
			// CloudFormation resource type schema:
			// {
			//   "description": "The name of the Lambda function, up to 64 characters in length. If you don't specify a name, AWS CloudFormation generates one.",
			//   "minLength": 1,
			//   "type": "string"
			// }
			Description: "The name of the Lambda function, up to 64 characters in length. If you don't specify a name, AWS CloudFormation generates one.",
			Type:        types.StringType,
			Optional:    true,
			Computed:    true,
			Validators: []tfsdk.AttributeValidator{
				validate.StringLenAtLeast(1),
			},
			PlanModifiers: []tfsdk.AttributePlanModifier{
				tfsdk.RequiresReplaceIf(func(ctx context.Context, state, config attr.Value, path *tftypes.AttributePath) (bool, diag.Diagnostics) {
					if config.Equal(state) || config.Equal(types.String{Null: true}) {
						return false, nil
					}

					return true, nil
				}, "require replacement if configuration value changes", "require replacement if configuration value changes"),
			},
		},
```

### Proposal

```go
type Value interface {
	// ... existing methods ...

	// IsNull returns true if the value is null.
	IsNull() bool

	// IsUnknown returns true if the value is unknown.
	IsUnknown() bool
}
```

For any `attr.Value` that potentially do not understand null/unknown, they can always return false for both methods. The implementation above then becomes:

```go
			PlanModifiers: []tfsdk.AttributePlanModifier{
				tfsdk.RequiresReplaceIf(func(ctx context.Context, state, config attr.Value, path *tftypes.AttributePath) (bool, diag.Diagnostics) {
					if config.Equal(state) || config.IsNull() {
						return false, nil
					}

					return true, nil
				}, "require replacement if configuration value changes", "require replacement if configuration value changes"),
			},
```

**Comment by bflad** [comment]
Another use case is attempting to write a generic state -> plan attribute plan modifier for Computed attributes:

```go
type computedValueDoesNotChangeModifier struct {}

func (m computedValueDoesNotChangeModifier) Description(ctx context.Context) string {
	return "Value does not change after creation."
}

func (m computedValueDoesNotChangeModifier) MarkdownDescription(ctx context.Context) string {
	return m.Description()
}

func (m computedValueDoesNotChangeModifier) Modify(ctx context.Context, req tfsdk.ModifyAttributePlanRequest, resp *tfsdk.ModifyAttributePlanResponse) {
	// Do nothing for Create
	if req.AttributeState == nil || req.AttributeState.IsNull() {
		return
	}

	resp.AttributePlan = req.AttributeState
}
```

**Comment by paddycarver** [comment]
I think we talked about this previously, and discarded the idea because it opened the door for inconsistent implementations (i.e., `IsNull()` returns `false` but `ToTerraformValue` returns `nil`.

Does a `tfsdk.ValueIsNull()` and `tfsdk.ValueIsUnknown()` address this?

**Comment by bflad** [comment]
> I think we talked about this previously, and discarded the idea because it opened the door for inconsistent implementations (i.e., IsNull() returns false but ToTerraformValue returns nil.

What if we recommend the `ToTerraformValue()` implementation if `IsNull()` would otherwise be complicated to implement (e.g. its not just a field on the custom type)?

> Does a tfsdk.ValueIsNull() and tfsdk.ValueIsUnknown() address this?

Likely, since I presume the implementation would be something like the following:

```go
func ValueIsNull(ctx context.Context, val attr.Value) (bool, error) {
  tfValRaw, err := val.ToTerraformValue(ctx)

  return tfValRaw == nil, err
}
```

That implementation does require more gymnastics though since you either have to pass back the error, making it not a simple conditional helper, or as a cursed implementation, swallow the error.

How discoverable are these `tfsdk` methods though, especially as the package is continuing to grow in surface area? As a provider developer, how do I know to look in the `tfsdk` package for these when I'm working with `attr.Value` in the documentation or language server hints? Maybe this would be less of a mental hurdle (and `tfsdk` less of a "grab bag" Go package) if `Value` handling helpers were in their own package that would be easy to reference as a whole.

**Comment by bflad** [comment]
I also think that encouraging or requiring custom implementations to explicitly think about null and unknown values, e.g. by introducing these methods, might make for overall less problematic implementations such as those only backed by built-in, non-pointer Go types since a developer would need to 🤔  whether what they are doing might be problematic. I guess I lean towards prioritizing ease of use, since this is likely a common use case, over potential risks with inconsistent custom implementations.

**Comment by bflad** [comment]
Partially related: #201 and #221

**Comment by bflad** [comment]
After #231, the `ToTerraformValue()` method on `attr.Value`s can be used to get a `tftypes.Value` directly, which has `IsNull()` and `IsKnown()`methods.
