### ISSUE TITLE
tfsdk: Standardize Response Type Diagnostics Handling

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-framework#196]
### Module version

```
v0.4.2
```

### Description

A portion of the `...Response` types include methods for directly adding diagnostics, such as `(CreateResourceReponse).AddError(summary string, detail string)`. A full listing can be seen below:

| Type | Diagnostic Methods |
|------|--------------------|
| ConfigureProviderResponse | yes |
| CreateResourceResponse | yes |
| DeleteResourceResponse | yes |
| ImportResourceStateResponse | no |
| ModifyAttributePlanResponse | yes |
| ModifyResourcePlanResponse | yes |
| ReadDataSourceResponse | yes |
| ReadResourceResponse | yes |
| UpdateResourceResponse | yes |
| ValidateAttributeResponse | no |
| ValidateDataSourceConfigResponse | no |
| ValidateProviderConfigResponse | no |
| ValidateResourceConfigResponse | no |

The `diag` package introduced in v0.3.0 includes these methods on the `diag.Diagnostics` type. Therefore, each of these response types with a `Diagnostics` field automatically inherit the ability to do `resp.Diagnostics.AddError()` and the like without needing the additional surface area of including them on the response types.

### Proposal

Either all response types, for consistency, should always include the diagnostics methods or none should since it is now automatically supported.

**Comment by paddycarver** [comment]
My vote would be that we remove them in favor of the `resp.Diagnostics` methods.
