### ISSUE TITLE
Fix truncated diagnostics in go-cmp diffs in tests

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#217]
We use [go-cmp](https://github.com/google/go-cmp) pretty extensively in our tests to compare values. This works great, except when comparing diagnostics. As documented in google/go-cmp#279, our diagnostic detail output usually gets truncated, mostly right after telling us that an error occurred and it's always a problem with the provider. This leads to us littering logging statements around logging error output in our tests, which feels suboptimal.

I _think_ we can write a customer [Reporter](https://pkg.go.dev/github.com/google/go-cmp/cmp#Reporter) but that seems like a large-ish undertaking, requires us to pass an option to all our calls to `cmp.Diff`, and I'm confused about whether we can use that for `Diff` or if it's just for `Equal`.

Seeing how google/go-cmp#279 resolves may help guide what we want to do here.

**Comment by bflad** [comment]
Now tracking upstream at https://github.com/google/go-cmp/issues/264

**Comment by bflad** [comment]
A unit testing workaround is looping through diagnostics with `t.Logf()` with something like:

```go
if diff := cmp.Diff(resp.Diagnostics, testCase.expectedDiagnostics); diff != "" {
  for _, diagnostic := range resp.Diagnostics {
    t.Logf("unexpected diagnostic: %s", diagnostic)
  }
  t.Fatalf("unexpected diagnostics difference: %s", diff)
}
```

While we could say this is the desired implementation until there is further clarity on go-cmp changes or recommendations, this is hard to "enforce" so it is generally used as a temporary unit test troubleshooting step, rather than inconsistently implemented across the various unit testing.

**Comment by bflad** [comment]
We're still waiting on https://github.com/google/go-cmp/issues/264 upstream for this and trying to pare down the issue tracker to actionable items, for _reasons_. Let's stay subscribed upstream and use the `t.Logf()` workaround for now until someone has some time to investigate further.
