### ISSUE TITLE
Debugger-Debugging mode

### ISSUE THREAD

**Issue by roperto** [hashicorp/terraform-plugin-framework#239]
### Use-cases
When developing a provider, using just "log based" debugging may not be the best tool to use.

### Attempted Solutions
Using `.Debug` instead of `.Serve` or using the `--debug` parameter. Looking into the code it seems like it is planned but not implemented:

https://github.com/hashicorp/terraform-plugin-framework/blob/574e52cdb9f8015c92cbe28a65dd008456a0726c/tfsdk/serve.go#L47

### Proposal
Implementing the `--debug` is ideal, but if a workaround is provided for the meantime to be able to connect the debugger an an IDE it would be appreciated.

### References
none

**Comment by roperto** [comment]
Note: I created this question on StackOverflow -- for some silly reason I checked there before checking here.

https://stackoverflow.com/questions/70487581/how-to-debug-debugger-based-debugging-a-terraform-provider-using-the-framework

**Comment by bflad** [comment]
Submitted https://github.com/hashicorp/terraform-plugin-framework/pull/243, which is similar to the Terraform Plugin SDK implementation.

**Comment by bflad** [comment]
On main and in the next release (v0.6.0), there is a now a `Debug` field in `tfsdk.ServeOpts` which can be used with debuggers, such as `delve`. This will be documented in https://terraform.io/plugin/framework, but briefly, framework providers can be setup with a `main` function such as:

```go
func main() {
	var debug bool

	flag.BoolVar(&debug, "debug", false, "set to true to run the provider with support for debuggers like delve")
	flag.Parse()

	ctx := context.Background()
	serveOpts := tfsdk.ServeOpts{
		Debug: debug,
		Name:  "registry.terraform.io/bflad/framework",
	}

	err := tfsdk.Serve(ctx, provider.New, serveOpts)

	if err != nil {
		log.Fatalf("Error serving provider: %s", err)
	}
}
```

Then a headless delve session can be started, or if using VSCode, a `.vscode/launch.json` configuration such as the below will automatically setup built-in Go debug support:

```json
        {
            "name": "Debug - Attach External CLI",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}",
            "env": {},
            "args": [
                "-debug",
            ],
        }
```
