### ISSUE TITLE
How to I do ConflictsWith?

### ISSUE THREAD

**Issue by frankgreco** [hashicorp/terraform-plugin-framework#241]
### Module version

```
v0.5.0
```

How is `ConflictsWith` supported in the framework?

**Comment by bflad** [comment]
Hey again, @frankgreco 👋 

While there is not yet a canonical implementation or specific documentation around functionality that is similar to the [`helper/schema.Schema` type `ConflictsWith` field from Terraform Plugin SDK](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Schema.ConflictsWith), it should however be at least somewhat achievable with the current framework using the validation support. Off the top of my head, a potentially useful (and generic) reference implementation may be the [`OneOfRequired` helper in the awscc provider](https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/validate/required.go), however that is written for a specific use case of validating conflicting keys within the same object if I recall.

In general though, there are two approaches that should be workable whether its an attribute level validator or resource/data source level validator.

In the attribute validator case:

- The current attribute can be checked whether it is null or unknown given the `AttributeConfig` of the request, returning success early.
- Passed in attribute path(s) can be checked whether they are null or unknown given the `Config` of the request, returning an error diagnostic if there is a known value.

In the resource/data source/provider validator case, it is similar to the above, however everything will need to be based on the `Config` of the request while returning error diagnostics if multiple attribute paths have values.

The [Validation page](https://www.terraform.io/plugin/framework/validation) of the Terraform website documentation goes into more details about how either of these validators can be implemented.

**Comment by frankgreco** [comment]
Thanks @bflad 

I had thought about implementing my own validation type to accomplish this but wanted to check if there was something more "official" first. I'm guessing an explicit `.ConflictsWith` wasn't added because at the end of the day it's just another validation?

The only gap I see with this is who the docs generation will show that elements conflicts with another? As it stands right now, if I implement my own validator, the TF docs generator I'm using won't pass this info along.

**Comment by bflad** [comment]
> I'm guessing an explicit .ConflictsWith wasn't added because at the end of the day it's just another validation?

Correct. 👍  The hope is this framework provides enough functionality to create higher level abstractions on top, such as this. Over time some of these common use cases will likely be collected somewhere, however this hasn't been determined yet.

> The only gap I see with this is who the docs generation will show that elements conflicts with another? As it stands right now, if I implement my own validator, the TF docs generator I'm using won't pass this info along.

I believe this must be manually done at the moment right now by updating the `Description` or `MarkdownDescription` field of the `Attribute`. Validators are currently required to implement `Description` and `MarkdownDescription` method with the hopes that at some point in the future, there will be some additional framework-based solution that can then extract this information for usage by outside tooling such as documentation generation.

**Comment by frankgreco** [comment]
@bflad Thanks! I'll close this then.

I'll humbly add that unless there's a common validator that will implement `ConflictsWith` that everyone can just import, everyone that eventually migrates to the framework will need to write their own.

**Comment by frankgreco** [comment]
For those that might stumble across this, I wrote [this validator](https://github.com/frankgreco/terraform-helpers/blob/master/validators/conflicts_with.go) that should handle the majority of cases.
