### ISSUE TITLE
Can't have empty provider block schema

### ISSUE THREAD

**Issue by appilon** [hashicorp/terraform-plugin-framework#250]
### Module version

```
v0.5.0
```

### Relevant provider source code

```go
func (p provider) GetSchema(context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{}, // leaving Attributes unset also produces the same error
	}, nil
}
```
Adding an attribute that I don't need get's rid of the issue
```
func (p provider) GetSchema(context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{
			"noop": {
				Type:     types.StringType,
				Optional: true,
			},
		},
	}, nil
}
```

### Terraform Configuration Files

```hcl
resource "example_resource" "test" {
}
```

### Expected Behavior

Having a provider that happens to not have any provider block schema (a simple/experimental provider) is allowed.
### Actual Behavior

```
╷
│ Error: Failed to load plugin schemas
│
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/appilon/test: failed to retrieve schema from provider
│ "registry.terraform.io/appilon/test": 2 problems:
│
│ - Error converting provider schema: The provider schema couldn't be converted into a usable type. This is always a problem with the provider. Please report the following to the provider developer:
│
│ must have at least one attribute or block in the schema
│ - missing provider schema..
╵
```

**Comment by appilon** [comment]
I do see that there is mention of
>must have at least one attribute or block in the schema
Just wondering if it's possible to lift that requirement. It's very likely the hobby provider I am working on will eventually need something in the provider block, so not likely a big problem for many providers

**Comment by bflad** [comment]
I wasn't able to find any particular reason for this restriction and verified a provider works okay against Terraform CLI 1.1 with no attributes or blocks. Submitted https://github.com/hashicorp/terraform-plugin-framework/pull/252 if you'd like to review removing that error handling.
