### ISSUE TITLE
Support for anonymous nested struct

### ISSUE THREAD

**Issue by miton18** [hashicorp/terraform-plugin-framework#309]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v0.6.1
```

### Relevant provider source code

```go
type AdvancedApp struct {
	App                          // all common config
	DevDependencies types.Bool   `tfsdk:"dev_dependencies"`
	StartScript              types.String `tfsdk:"start_script"`
}

type App struct {
	ID               types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
}

....
// In Create handler
var app AdvancedApp
resp.Diagnostics.Append(req.Plan.Get(ctx, &app)...)
if resp.Diagnostics.HasError() {
    return
}
```

### Terraform Configuration Files

not relevant

### Debug Output
```
resource_advancedapp_test.go:33: Step 1/1 error: Error running apply: exit status 1
        
        Error: Value Conversion Error
        
          with provider_advancedapp.tf-test-node-1651219284060,
        An unexpected error was encountered trying to convert tftypes.Value into
        provider.AdvancedApp. This is always an error in the provider. Please report the
        following to the provider developer:
        
        error retrieving field names from struct tags: need a struct tag for "tfsdk"
        on App
```

### Expected Behavior
terraform-plugin-framework should support nested structs.

### Actual Behavior
The previous error. 
Can come from https://github.com/hashicorp/terraform-plugin-framework/blob/main/tfsdk/plan.go#L22

### Motivation
We have several resources with common schema properties, we don't want to implement them in each resources.
`GetSchema()` can easily concat App schema and AdvancedApp schema.
But we need to be able to `req.Plan.Get()` them in a struct.

**Comment by bflad** [comment]
I'm going to merge this issue with #242 since they are very related. This is just to consolidate discussions and efforts in one place. 👍

**Comment by miton18** [comment]
Instead, can you close with the merge, this seems to be not merged soon...
