### ISSUE TITLE
Have something like `ValueFrom` as the opposite of `ValueAs`

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-plugin-framework#323]
### Module version

```
0.7.0
```

### Use-cases

Currently I have sets/lists of objects and they're easy to flip from `types.Object` to my struct with `.As`, however, when I want to set them in state, I have to make them `types.List`/`types.Set` again and it gets to be a little cumbersome to always declare a list with type object elements, its attr types, then create an object with the same attr types, etc. It would be nice to be able to do a similar thing to get them back to `types.Object`

### Attempted Solutions

I haven't implemented anything yet, but will update when I get the chance!

### References

[ValueAs](https://github.com/hashicorp/terraform-plugin-framework/blob/main/tfsdk/value_as.go)

**Comment by rschmied** [comment]
this would be pretty cool.  I'm struggling with the exact same problem and the way this has to be done currently is pretty awkward. Constantly wondering if I'm simply not seeing "the way" or if there's something missing in the framework.  This issue underlines my assumption that it's the latter.

I'm dealing with a nested list of objects  `list[object[attributes, list[object[attributes]]` and it's a pain to work with such a construct. I want to set elements in the nested list to "unknown" when the plan is modified... *hair-on-fire*

This relates to [my comment here](https://github.com/hashicorp/terraform-plugin-framework/issues/191#issuecomment-1129302605)
