### ISSUE TITLE
Validation issue with first instance resources create using `count=n`

### ISSUE THREAD

**Issue by chrismarget** [hashicorp/terraform-plugin-framework#388]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v0.9.0
```

### Relevant provider source code

```go
const (
	minVal = 1    // validation limit
	maxVal = 3    // validation limit
)

func (o bogusValidator) Validate(ctx context.Context, req tfsdk.ValidateAttributeRequest, resp *tfsdk.ValidateAttributeResponse) {
	var bogusAttr types.Int64
	diags := req.Config.GetAttribute(ctx, req.AttributePath, &bogusAttr)
	resp.Diagnostics.Append(diags...)

	if bogusAttr.Value < minVal || bogusAttr.Value > maxVal {
		resp.Diagnostics.AddError(
			"Value out of range",
			fmt.Sprintf("Valid range: %d - %d, value %d is out of range", minVal, maxVal, bogusAttr.Value),
		)
	}
}

func (r resourceBogusType) GetSchema(_ context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{
			"validated": {
				Type:          types.Int64Type,
				Required:      true,
				PlanModifiers: tfsdk.AttributePlanModifiers{tfsdk.RequiresReplace()},
				Validators:    []tfsdk.AttributeValidator{bogusValidator{}},
			},
		},
	}, nil
}

```

### Terraform Configuration Files

```hcl
resource "tfsdkvalidationdemo_bogus" "x" {
  count = 3
  validated = count.index + 1
}
```

### Debug Output

https://gist.github.com/chrismarget/b59a348c0303306186f8fd83854fff74

### Expected Behavior

`plan` should have produced a plan which includes 3 resources, like this:

```
  # tfsdkvalidationdemo_bogus.x[0] will be created
  + resource "tfsdkvalidationdemo_bogus" "x" {
      + validated = 1
    }

  # tfsdkvalidationdemo_bogus.x[1] will be created
  + resource "tfsdkvalidationdemo_bogus" "x" {
      + validated = 2
    }

  # tfsdkvalidationdemo_bogus.x[2] will be created
  + resource "tfsdkvalidationdemo_bogus" "x" {
      + validated = 3
    }
```

### Actual Behavior

The relevant error output from the validation steps:

```
│ Error: Value out of range
│ 
│   with tfsdkvalidationdemo_bogus.x,
│   on main.tf line 11, in resource "tfsdkvalidationdemo_bogus" "x":
│   11: resource "tfsdkvalidationdemo_bogus" "x" {
│ 
│ Valid range: 1 - 3, value 0 is out of range
```

Two interesting things here:

1) The resource which fails is: `tfsdkvalidationdemo_bogus.x`, not `tfsdkvalidationdemo_bogus.x[0]`

2) The value for attribute `validated` in this resource is `0`, which should never have been produced by the HCL `count.index + 1`

I've done some experiments with changing the `minVal` and `maxVal` constants in my code and running afoul of validation limits on both ends. It looks like the problem is unique to the first instance of the iterable resource which hits the validation logic. Only that first instance is presented as a single resource (no `[0]` notation in the error), and with the wrong value in that resources `validated` attribute. Subsequent iterations of the same resource seem to be okay.

### Steps to Reproduce

A project containing the provider code and the relevant HCL is here:

https://github.com/chrismarget/terraform-provider-tfsdkvalidationdemo.git

### References

Nope.

**Comment by bflad** [comment]
Hi @chrismarget 👋  Thank you for raising this and sorry you ran into trouble here.

Are you able to quickly verify that the incoming value is not unknown? e.g. before the `bogusAttr.Value` checking

```go
if bogusAttr.IsUnknown() {
  return
}
```

While the plan is showing the evaluated attribute value for the expression, the static configuration validation phase which happens beforehand, may not have that information yet.

We are also working on documenting some of these common use case validators as part of #240, but https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework-validators/int64validator#Between may also negate the need for a custom validator unless there's other logic at play. 👍

**Comment by chrismarget** [comment]
`Validate()` now reads:

```go
func (o bogusValidator) Validate(ctx context.Context, req tfsdk.ValidateAttributeRequest, resp *tfsdk.ValidateAttributeResponse) {
	var bogusAttr types.Int64
	diags := req.Config.GetAttribute(ctx, req.AttributePath, &bogusAttr)

	if bogusAttr.IsUnknown() {
		return
	}

	resp.Diagnostics.Append(diags...)

	if bogusAttr.Value < minVal || bogusAttr.Value > maxVal {
		resp.Diagnostics.AddError(
			"Value out of range",
			fmt.Sprintf("Valid range: %d - %d, value %d is out of range", minVal, maxVal, bogusAttr.Value),
		)
	}
}
```

The plan succeeds now.

I think this is consistent with the peculiar handling of the first instance of the resource (`tfsdkvalidationdemo_bogus.x` rather than `tfsdkvalidationdemo_bogus.x[0]`), and explains why the Value is the Go default for a number type.
