### ISSUE TITLE
Issue with terraform-provider-hashicups-pf provider for v0.9.0

### ISSUE THREAD

**Issue by shenda1** [hashicorp/terraform-plugin-framework#411]
### Module version

```
Terraform Version: v1.2.4
Terraform Plugin Framework Version: v0.9.0
```

### Relevant provider source code

```go

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"terraform-provider-hashicups-pf/hashicups"
)

func main() {
	tfsdk.Serve(context.Background(), hashicups.New, tfsdk.ServeOpts{
		Name: "hashicups",
	})
}
```

### Expected Behavior

terraform-hashicups-provider binary should be created.

### Actual Behavior

terraform-hashicups-provider binary is not created. Also unit tests are not included like https://github.com/hashicorp/terraform-provider-hashicups

### Steps to Reproduce

Run below command:
`go build -o terraform-provider-hashicups`

### References
https://github.com/hashicorp/terraform-provider-hashicups-pf/issues/17

**Comment by bflad** [comment]
Hi @shenda1 👋 Thank you for raising this and sorry you ran into trouble here.

Recent versions of the framework now use the [`providerserver` package](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/providerserver) to handle the [provider server](https://www.terraform.io/plugin/framework/provider-servers) parts of a provider. For example:

```go
func main() {
	providerserver.Serve(context.Background(), exampleprovider.New(), providerserver.ServeOpts{
		Address: "registry.terraform.io/example-namespace/example",
	})
}
```

I have submitted the terraform-plugin-framework dependency updates for the tutorial provider here: https://github.com/hashicorp/terraform-provider-hashicups-pf/pull/18

For further bug reports or feature requests with that tutorial or its provider, please create issues in that provider's issue tracker. Thanks again.
