### ISSUE TITLE
Reference nested fields in other resources

### ISSUE THREAD

**Issue by marcoandredinis** [hashicorp/terraform-plugin-framework#412]
### Module version
```
github.com/hashicorp/terraform-plugin-framework v0.9.0
```

### Relevant provider source code
Slightly modified version of the https://github.com/hashicorp/terraform-provider-scaffolding-framework
This version adds two extra fields:
```go
		Attributes: map[string]tfsdk.Attribute{
			"id": {
				Computed:            true,
				MarkdownDescription: "Example identifier",
				PlanModifiers: tfsdk.AttributePlanModifiers{
					tfsdk.UseStateForUnknown(),
				},
				Type: types.StringType,
			},
			"metadata": {
				MarkdownDescription: "Meta info",
				Optional:            true,
				Attributes: tfsdk.SingleNestedAttributes(map[string]tfsdk.Attribute{
					"name": {
						Description: "Name is an object name",
						Required:    true,
						Type:        types.StringType,
					},
				}),
			},
		},
```

### Terraform Configuration Files
The following fails to run with

```hcl
resource "scaffolding_example" "test" {
  metadata = {
    name = "abc"
  }
}
resource "scaffolding_example" "test2" {
  metadata = {
    name = scaffolding_example.test.metadata.name
  }
}
```

### Debug Output
Error when running Acceptance Tests
```
TF_ACC=1 go test ./... -v  -timeout 120m
?       github.com/hashicorp/terraform-provider-scaffolding-framework   [no test files]
=== RUN   TestAccExampleResource
    example_resource_test.go:10: Step 1/1 error: Error running pre-apply refresh: exit status 1
        
        Error: Unsupported attribute
        
          on terraform_plugin_test.tf line 9, in resource "scaffolding_example" "test2":
           9:     name = scaffolding_example.test.metadata.name
        
        This value does not have any attributes.
--- FAIL: TestAccExampleResource (0.08s)
```

### Expected Behavior
It was expected that this code ran without any issues

### Actual Behavior
Fails with error above

### Steps to Reproduce

Clone `https://github.com/hashicorp/terraform-provider-scaffolding-framework`
Add the schema above to the `example_resource.go`
Change `example_resource_test.go` and `testAccExampleResourceConfig` with the config above
You must also replace the Steps list with this single step:
```go
Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccExampleResourceConfig(),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("scaffolding_example.test", "metadata.name", "abc"),
					resource.TestCheckResourceAttr("scaffolding_example.test2", "metadata.name", "abc"),
				),
			},
		},
```

Run `make acctest`

### Workaround
If you change `name = scaffolding_example.test.metadata.name` to `name = (scaffolding_example.test).metadata.name` everything works as expected

**Comment by bflad** [comment]
Hi @marcoandredinis 👋 Thank you for raising this and sorry you ran into trouble here.

I have two clarification questions:

- Which version of Terraform CLI is being used?
- Does this only happen when using the terraform-plugin-sdk based acceptance testing framework or does it also occur in real Terraform configurations outside the testing framework (e.g. a regular `terraform apply` command)?

Thanks so much.

**Comment by bflad** [comment]
By the way, thank you for the easy reproduction. I was able to generate TRACE logging for everything with that repository and running:

```console
$ TF_ACC=1 TF_LOG=TRACE TF_ACC_LOG_PATH=/tmp/test.txt go test -count=1 -run='TestAccExampleResource' -v ./internal/provider
=== RUN   TestAccExampleResource
    example_resource_test.go:10: Step 1/1 error: Error running pre-apply refresh: exit status 1

        Error: Unsupported attribute

          on terraform_plugin_test.tf line 9, in resource "scaffolding_example" "test2":
           9: 	  name = scaffolding_example.test.metadata.name

        This value does not have any attributes.
--- FAIL: TestAccExampleResource (0.11s)
```

Gist of TRACE logging: https://gist.github.com/bflad/1fa2b2a3fd92eabb6596f6b1dfa853e7

**Comment by marcoandredinis** [comment]
Hey @bflad 
Thank you for getting back

So, the version is
```
Terraform v1.2.5
on linux_amd64
```

This also happens when running `terraform apply` on a "real" setting.

It's my understanding that you were able to reproduce the issue.
Did you also validate that adding `()` fixes the problem?
So, changing to
```tf
 name = (scaffolding_example.test).metadata.name
```

**Comment by bflad** [comment]
Hi @marcoandredinis 👋 I was able to validate that using the parenthesis in the configuration reference does indeed workaround the error.

From the TRACE logging, it appears this error is coming from Terraform itself while attempting to validate the Terraform configuration. Given that, I have raised https://github.com/hashicorp/terraform/issues/31527 in their issue tracker to follow up further on this. I would personally expect Terraform in this situation to either "just work" or provide a more helpful error message. 👍 

I'd like to keep this issue open here in case there happens to be anything we're doing wrong on our side, or in case others may run into this issue until it is hopefully resolved in some form in Terraform itself. Thanks again for your work here!

**Comment by bflad** [comment]
There is now a proposed fix upstream: https://github.com/hashicorp/terraform/pull/31532. If you're feeling really adventurous, you can try building Terraform using that PR branch to see how it behaves or we can wait until this gets released into a 1.2.x patch to verify it. 😄

**Comment by marcoandredinis** [comment]
It does seem to work as expected :+1: 

```shell
marco@lenix ~/p/terraform-provider-scaffolding-framework (main)> terraform version
Terraform v1.2.5
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.2.6. You can update by downloading from https://www.terraform.io/downloads.html
marco@lenix ~/p/terraform-provider-scaffolding-framework (main)> make testacc
TF_ACC=1 go test ./... -v  -timeout 120m
?       github.com/hashicorp/terraform-provider-scaffolding-framework   [no test files]
=== RUN   TestAccExampleResource
    example_resource_test.go:10: Step 1/1 error: Error running pre-apply refresh: exit status 1
        
        Error: Unsupported attribute
        
          on terraform_plugin_test.tf line 9, in resource "scaffolding_example" "test2":
           9:     name = scaffolding_example.test.metadata.name
        
        This value does not have any attributes.
--- FAIL: TestAccExampleResource (0.11s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-scaffolding-framework/internal/provider 0.117s
FAIL
make: *** [GNUmakefile:6: testacc] Error 1
```
```shell
marco@lenix ~/p/terraform-provider-scaffolding-framework (main)> terraform version
Terraform v1.3.0-dev
on linux_amd64
marco@lenix ~/p/terraform-provider-scaffolding-framework (main)> make testacc
TF_ACC=1 go test ./... -v  -timeout 120m
?       github.com/hashicorp/terraform-provider-scaffolding-framework   [no test files]
=== RUN   TestAccExampleResource
--- PASS: TestAccExampleResource (0.34s)
PASS
ok      github.com/hashicorp/terraform-provider-scaffolding-framework/internal/provider 0.342s
```

**Comment by bflad** [comment]
The fix for this has been merged upstream in Terraform core and will release with version 1.2.7 and the next 1.3.0 pre-release. 👍
