### ISSUE TITLE
tfsdk: Validate Block MaxItems and MinItems for Terraform 0.12-0.15.1 Compatibility

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-framework#421]
### Module version

```
v0.10.0
```

### Use-cases

When implementing `tfsdk.Block` schema definitions with `MaxItems` and/or `MinItems` fields set, e.g.:

```go
tfsdk.Block{
  // other fields omitted for brevity
  MaxItems: 2,
  MinItems: 2,
}
```

The prior terraform-plugin-sdk implemented configuration validation logic for list and set blocks for these fields until Terraform version 0.15.2 introduced the proper validation through HCL's configuration decoding validation support. Terraform versions between 0.12.0 and 0.15.1 implemented a conservative validation approach, which generally relied on terraform-plugin-sdk catching this class of configuration issue after decoding the configuration and during the `Validate*Config` RPCs.

### Attempted Solutions

Manually using an attribute validator, such as [`listvalidator.SizeBetween()`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework-validators@v0.4.0/listvalidator#SizeBetween), in the block definition.

### Proposal

When performing "attribute" validation on blocks, re-implement similar fallback validation logic to check the list/set block element counts against the defined `MaxItems` and `MinItems` fields if they are set above 0. This logic must double check that each element is known (not null or unknown).

### References

- https://github.com/hashicorp/terraform-provider-tls/pull/242
- https://github.com/hashicorp/terraform/pull/28424
- https://github.com/hashicorp/terraform-plugin-sdk/blob/b61403bc822f962eee39212bb131de93cfe903ae/helper/schema/schema.go#L1919-L1936

**Comment by bflad** [comment]
Another potential option here is dropping these two fields and requiring the usage of list/set validators, similar to attributes and nested attributes.

**Comment by detro** [comment]
> Another potential option here is dropping these two fields and requiring the usage of list/set validators, similar to attributes and nested attributes.

That would definitely be an option. After all, the reason for `Block` to be still around is retro-compatibility of TF configurations. If in FW we require them to use validators like any other Attribute, I see no issue in that.

**Comment by bflad** [comment]
One quirk of these fields are that they are currently represented in the protocol and used by tooling like terraform-plugin-docs in the block documentation. To keep documentation parity if the fields were removed, descriptions would require manual updates to include text around the number of expected elements.

Another weird potential benefit of removing these fields is that provider could return _all_ non-syntax-related configuration errors, rather than what I would imagine what happens today where Terraform would return early if this particular schema-based validation failed before it calls the provider validation.

I'll see what the product folks think about this next week and raise a separate issue if there is desire to go in that direction of that type of breaking change.
