### ISSUE TITLE
Consider Moving DataSource and Resource Type Names to Methods

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-framework#442]
### Module version

```
v0.11.0
```

### Use-cases

An oft requested feature of larger providers is removing the need for a single source code file that defines all data sources and resources for a provider.

For example, providers are defined with the following today:

```go
func (p ExampleProvider) GetDataSources(ctx context.Context) (map[string]provider.DataSourceType, diag.Diagnostics) {
	return map[string]provider.DataSourceType{
		"example_thing": ThingDataSourceType{},
	}, nil
}

func (p ExampleProvider) GetResources(ctx context.Context) (map[string]provider.ResourceType, diag.Diagnostics) {
	return map[string]provider.ResourceType{
		"example_thing": ThingResourceType{},
	}, nil
}
```

Another challenge is that the name is detached from the implementation, meaning that including the name inside any of the logic is a little more complicated than it should be, since it must be duplicated or put into a shared constant, etc.

### Attempted Solutions

It is possible to define looping logic which appends to the map, which is overly complicated for the goal when there are potentially dozens of groupings.

```go
func (p ExampleProvider) GetResources(ctx context.Context) (map[string]provider.ResourceType, diag.Diagnostics) {
	result := make(map[string]provider.ResourceType)

	for name, resourceType := range serviceX.Resources { // serviceX.Resources being its own map[string]provider.ResourceType
		result[name] = resourceType
	}

	for name, resourceType := range serviceY.Resources { // serviceY.Resources being its own map[string]provider.ResourceType
		result[name] = resourceType
	}

	return result
}
```

It is possible to define package-level variables containing the mappings of names to data sources and resources, then having each data source or resource add to that mapping via an `init` function. Using `init` functions in Go is generally discouraged and everything must exist within the same Go package.

### Proposal

_NOTE: This proposal implementation also includes details from #441_

Require each data source and resource to implement a new method which returns the type name, then replace the map returns from the provider with slices. Slices allow for easy expansion and the type name method would allow other logic to self-reference the name if necessary.

Given this post #441 code (which generally is split across Go files/packages, but shown altogether here for brevity):

```go
// missing methods omitted for brevity
var _ provider.Provider = &ExampleProvider{}

type ExampleProvider struct{ /* ... */ }

func (p ExampleProvider) GetDataSources(ctx context.Context) (map[string]datasource.DataSource, diag.Diagnostics) {
	return map[string]datasource.DataSource{
		"example_thing": ThingDataSource{},
	}, nil
}

func (p ExampleProvider) GetResources(ctx context.Context) (map[string]resource.Resource, diag.Diagnostics) {
	return map[string]resource.Resource{
		"example_thing": ThingResource{},
	}, nil
}

// missing methods omitted for brevity
var _ datasource.DataSource = ThingDataSource{}

type ThingDataSource struct{ /* ... */ }

// missing methods omitted for brevity
var _ resource.Resource = ThingResource{}

type ThingResource struct{ /* ... */ }
```

It can be reimagined as:

```go
// missing methods omitted for brevity
var _ provider.Provider = &ExampleProvider{}

type ExampleProvider struct{ /* ... */ }

func (p ExampleProvider) GetDataSources(ctx context.Context) ([]datasource.DataSource, diag.Diagnostics) {
	return []datasource.DataSource{
		ThingDataSource{},
	}, nil
}

func (p ExampleProvider) GetResources(ctx context.Context) ([]resource.Resource, diag.Diagnostics) {
	return []resource.Resource{
		ThingResource{},
	}, nil
}

// missing methods omitted for brevity
var _ datasource.DataSource = ThingDataSource{}

type ThingDataSource struct{ /* ... */ }

func (d ThingDataSource) GetTypeName(ctx context.Context) string {
  return "example_thing"
}

// missing methods omitted for brevity
var _ resource.Resource = ThingResource{}

type ThingResource struct{ /* ... */ }

func (r ThingResource) GetTypeName(ctx context.Context) string {
  return "example_thing"
}
```

Providers can then introduce separated packages, etc. with easier logic such as:

```go
// serviceX package
var Resources = []resource.Resource{
  ThingResource{},
}

var _ resource.Resource = ThingResource{} // implementation omitted for brevity

// provider package
func (p ExampleProvider) GetResources(ctx context.Context) ([]resource.Resource, diag.Diagnostics) {
	return []resource.Resource{
		serviceX.Resources...,
	}, nil
}
```

Another optional enhancement to this proposal could also introduce a similar `Provider` interface `GetTypeName()` method:

```go
func (p ExampleProvider) GetTypeName(ctx context.Context) string {
  return "example"
}
```

Then updating the `DataSource`/`Resource` interface methods to include that result as a parameter/field (where the framework would automatically inject the value):

```go
func (r ThingResource) GetTypeName(ctx context.Context, providerTypeName string) string {
  return strings.Join([]string{providerTypeName, "thing"}, "_")
}
```

Providers could then get even fancier and allow their separated packages to handle the type name details automatically:

```go
// generic service package
type Service struct{
  TypeName string
}

// serviceX package
var Service = service.Service{
  TypeName: "x",
}

type Resource struct{
  TypeName string
}

func (r Resource) GetService() service.Service {
  return Service
}

func (r Resource) GetTypeName(ctx context.Context, providerTypeName string) string {
  return strings.Join([]string{providerTypeName, r.GetService().TypeName, r.typeName}, "_")
}

var Resources = []resource.Resource{
  ThingResource{
    Resource{
      TypeName: "thing",
    },
  }
}

var _ resource.Resource = ThingResource{}

type ThingResource struct{
  Resource
}
```

The above can probably be done in much better Go code, but hopefully it illustrates the conceptual benefits.

**Comment by ewbankkit** [comment]
I assume the framework is responsible for detecting and reporting duplicate type names in the resources/data sources returned via the slices?

RE `Provider.GetTypeName` - Isn't the name already set in `main.go`'s `server.Serve()` call?

**Comment by bflad** [comment]
> I assume the framework is responsible for detecting and reporting duplicate type names in the resources/data sources returned via the slices?

Indeed, yeah -- we won't get compiler time checks for this anymore in the simple case (technically you could've still overwritten existing keys with the existing setup), so we'll likely need to return a new error diagnostic from `GetProviderSchema`.

> RE Provider.GetTypeName - Isn't the name already set in main.go's server.Serve() call?

It is there, but only sometimes. That provider address is given during production usage with `providerserver.Serve()`, but not during testing usage (e.g. `providerserver.NewProtocol6WithError()`) at the moment. We may be able to require it, but it'll make the testing setup a little redundant as the testing framework wants a map of provider names to implementations already.
