### ISSUE TITLE
Computed values within nested lists within nested sets are unset by the framework

### ISSUE THREAD

**Issue by liamcervante** [hashicorp/terraform-plugin-framework#479]
### Module version

```
v0.11.1
```

### Relevant provider source code

[PR reproducing the bug](https://github.com/hashicorp/terraform-provider-corner/pull/89/files)

### Terraform Configuration Files

```hcl
resource "tf6muxprovider_nested" "example" {
  set {
	id = "one"
	list {
	}
	list {
	}
  }
  set {
	id = "two"
  }
}
```

### Debug Output

N/A, the error is reproduced in a test case in the PR

### Expected Behavior

The test case in the PR should pass.

### Actual Behavior

```
=== RUN   TestAccResourceNested
    nested_resource_test.go:11: Step 1/1 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # tf6muxprovider_nested.example will be updated in-place
          ~ resource "tf6muxprovider_nested" "example" {
                id = "XVlBzgba"
        
              - set {
                  - id = "two" -> null
        
                  - list {
                      - id = "iCMRAjWw" -> null
                    }
                  - list {
                      - id = "hTHctcuA" -> null
                    }
                }
              + set {
                  + id = "two"
        
                  + list {
                      + id = (known after apply)
                    }
                  + list {
                      + id = (known after apply)
                    }
                }
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccResourceNested (0.46s)
```

### Steps to Reproduce

1. Checkout the branch in terraform-provider-corner (or the forked repo)
2.  `TF_ACC=1 go test internal/tf6muxprovider/provider1/*.go`

### References

- https://github.com/hashicorp/terraform-provider-corner/pull/89
- https://github.com/hashicorp/terraform-plugin-framework/issues/183
- https://github.com/hashicorp/terraform-plugin-framework/issues/293
- https://github.com/hashicorp/terraform-plugin-framework/issues/302

**Comment by bflad** [comment]
Hi @liamcervante 👋 Thanks for raising this.

I wonder if this may be resolved with #468 and v0.12.0, which was released yesterday. Under the hood, sets are a slice of elements similar to lists, but previously the framework would use path-based lookups and data setting as it traversed deeper into collection types. Trying to doing this with sets, which treat the whole value of the set element as part of the path, was problematic as underlying values would change from null to unknown, etc. The new release aligns plan modification with the underlying slice elements, so that class of issue should no longer be present.

I'm going to try rebasing the corner PR, since that repository just had its dependency upgraded, to see if maybe we resolved this. 👍

**Comment by liamcervante** [comment]
Hi Brian!

Thanks so much for this, yes I agree that this issue is fixed.

However, I think I've found another one. This can be reproduced with my latest commit to the same branch I used previously: https://github.com/liamcervante/terraform-provider-corner/commit/f6f20375f5295ddf9f4d52e95ae6ae5e9cb9683c

Basically, emply blocks within nested lists are breaking now as the framework is setting the value for these nested blocks as null instead of an empty list. I think the issue is [here](https://github.com/hashicorp/terraform-plugin-framework/blob/main/internal/fwserver/block_plan_modification.go#L163), as the ModifyAttributePlanRequest isn't setting the Attribute[Config|Plan|State]. This in comparison to the set operation [here](https://github.com/hashicorp/terraform-plugin-framework/blob/main/internal/fwserver/block_plan_modification.go#L316) which is setting those values.

I can leave this issue open tracking this, or file a new one. Which would you prefer? I could even have a go at fixing this myself as it seems relatively straightforward, but that might not be the process. Let me know!

**Comment by liamcervante** [comment]
I have found another issue, but I think it's different enough that I will close this and create a new one.
