### ISSUE TITLE
Define Tuple type

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-framework#54]
Implementation similar to @bflad 's `Set` type. Can't do this in SDKv2, but parity w/ protocol.

**Comment by apparentlymart** [comment]
The tuple type kind is honestly rather odd and isn't something I'd generally expect folks to write in a type constraint... it's mainly there to fill in the missing spot that made our type system not a superset of JSON's, and used in dynamically-typed situations like the argument to `jsonencode`, or similar sorts of things like the `kubernetes_manifest` resource type in the `hashicorp/kubernetes` provider.

We did still include type constraint syntax for it in the language, more for completeness than anything else, and a similar "completeness" argument could apply here too, but I'd guess it's more likely that tuples will appear mainly as part of arguments that are dynamically-typed and so provider code will _probably_ end up converting it immediately to `[]interface{}` by reflection anyway. :thinking:

**Comment by bookshelfdave** [comment]
We're going to close this for now. If there's a need for tuples at some point in the future, please create a new issue with the use case.
