### ISSUE TITLE
StateUpgrader only works with deprecated APIs

### ISSUE THREAD

**Issue by iwarapter** [hashicorp/terraform-plugin-framework#572]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v0.17.0
```

### Relevant provider source code

```go
return map[int64]resource.StateUpgrader{
  0: {
    PriorSchema: &schema.Schema{
      Attributes: map[string]schema.Attribute{
	"id": schema.StringAttribute{
          Required: true,
	},
      },
    },
    StateUpgrader: func(...
```

### Terraform Configuration Files

```hcl
N/A
```

### Expected Behavior

The new separated APIs should work with StateUpgraders, i'm assuming this hasn't been done as it's planned for the removal of the deprecated APIs.

### Actual Behavior

Doesn't compile.

**Comment by bflad** [comment]
Thank you for catching this, @iwarapter. 😄  This was a miss on my part during the `tfsdk.Schema` deprecation effort. The intention would be to require `resource/schema.Schema` there, similar to the other resource schema handling. It looks like you submitted #573 to cover this, which we can review shortly.

**Comment by bflad** [comment]
#573 was merged. 👍
