### ISSUE TITLE
Update PlanModifyString implementation to clarify its usage

### ISSUE THREAD

**Issue by Integralist** [hashicorp/terraform-plugin-framework#596]
I open a PR #595 (recently merged) that fixed an incorrect field reference and in the PR I questioned the implementation of the PlanModifyString method defined in https://github.com/hashicorp/terraform-plugin-framework/blob/main/website/docs/plugin/framework/resources/plan-modification.mdx under the heading "Creating Attribute Plan Modifiers". 

@bflad mentioned...

> This code example might be best served with an update to check !req.ConfigValue.IsNull() for clarity (and to allow prior plan modification to set a null plan value successfully), but it might be best to create a separate issue/PR to discuss this type of example change further.

So here I am 🙂

**Comment by bflad** [comment]
@bendbennett while we are updating the plan modification page for default value support, I think this will be covered as well with those code changes. 👍

**Comment by bflad** [comment]
This code was updated as part of #668 and will release with terraform-plugin-framework version 1.2.0 🔜 . If there are further documentation suggestions with plan modifier handling, please raise a new issue. 👍
