### ISSUE TITLE
Support for multi-type attributes in providers

### ISSUE THREAD

**Issue by tyler-dunkel** [hashicorp/terraform-plugin-framework#611]
### Module version

```
1.01
```

### Use-cases

I have a data block in my plugin that I want to be able to use an any type for one of its attributes. The attribute could theoretically accept anything from strings, numbers, bools, lists, objects, etc. The end goal is to allow users to be able to set values for variables in their modules statically (as part of the provider's pattern). Because we dont know the variable types until runtime, we are not able to set the type of the attribute where they can set the value they want to use for the variable. 

### Attempted Solutions

Right now the current solution is to wrap the variable values in JSON but that is not a great solution.
### Proposal

Are we able to use the `any` variable type that can be used in other areas of terraform?

**Comment by bflad** [comment]
Hi @tyler-dunkel 👋 Thank you for raising this. I believe this is covered by https://github.com/hashicorp/terraform-plugin-framework/issues/147 so I'm going to close this as a duplicate, but please feel free to comment on that other issue with additional use case information.
