### ISSUE TITLE
Integration with terraform-plugin-log

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-framework#63]
As [`terraform-plugin-log`](https://github.com/hashicorp/terraform-plugin-log) is the recommended method for logging from new providers, `terraform-plugin-framework` should provide the functionality described in the documentation:

> For most plugin authors, building on an SDK or framework, the SDK or framework will take care of injecting a logger using New.

**Comment by paddycarver** [comment]
hashicorp/terraform-plugin-go#93 is a prerequisite for this. Once the framework can depend on that code, `tflog.Debug(ctx, "hello, world")` and friends will Just Work&trade;, though the framework can probably do more to inject helpful values into the logging context.

**Comment by paddycarver** [comment]
This is addressed in #234.
