### ISSUE TITLE
UseStateForUnknown does not work with types.List in model and ListNestedAttribute in schema

### ISSUE THREAD

**Issue by shiyuhang0** [hashicorp/terraform-plugin-framework#644]
### Module version

```
v1.1.1
```

### Relevant provider source code

model define:

```go
type ImportResourceModel struct {
	AllCompletedTables         types.List   `tfsdk:"all_completed_tables"`
}
```

schema define: 
```
			"all_completed_tables": schema.ListNestedAttribute{
				MarkdownDescription: "Import task all completed tables",
				Computed:            true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
				NestedObject: schema.NestedAttributeObject{
					PlanModifiers: []planmodifier.Object{
						objectplanmodifier.UseStateForUnknown(),
					},
					Attributes: map[string]schema.Attribute{
						"table_name": schema.StringAttribute{
							MarkdownDescription: "Import task all completed tables - table name",
							Computed:            true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
							},
						},
						"result": schema.StringAttribute{
							MarkdownDescription: "Import task all completed tables - result",
							Computed:            true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
							},
						},
						"message": schema.StringAttribute{
							MarkdownDescription: "Import task all completed tables - message",
							Computed:            true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
							},
						},
					},
				},
			},
```

convert code

```
objectMap := map[string]attr.Type{
		"table_name": types.StringType,
		"result":     types.StringType,
		"message":    types.StringType,
	}
	listValue, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: objectMap}, allCompletedTables)
	data.AllCompletedTables = listValue
```

### Terraform Configuration Files

```hcl
```

### Debug Output

<img width="502" alt="image" src="https://user-images.githubusercontent.com/52435083/215736187-6b1553af-746c-4bad-9f13-9a9d7379b892.png">

### background

I want to define `all_completed_tables` filed as a read-only filed.  So, I use `computed` and `UseStateForUnknown` in schema.
But when I change the configuration file and apply, I find that the  `all_completed_tables` can't read values from state. It changed to null according to the diff.

Maybe it is because that I use `ListNestedAttribute` in schema and the nested attr can't apply `UseStateForUnknown`. And The framework does not provide something like `types.ListNested` when I define my `ImportResourceModel`.

I wonder if my guess is right and how to avoid the read-only filed change.

### Expected Behavior

read-only filed will not be changed.

### Actual Behavior

read-only filed changed

**Comment by bflad** [comment]
Hi @shiyuhang0 👋 Thank you for raising this issue and sorry you are running into trouble here.

I believe we will need additional information in order to help troubleshoot this issue:

- Either a full reproduction codebase and necessary steps
- Or at least the full definition of the `Read` and `Schema` methods, including the definitions of any called methods/functions

For troubleshooting purposes, you can skip the `Read` logic by ensuring the Terraform state looks as it should after `terraform apply`, then calling `terraform plan` with `-refresh=false`.

**Comment by bflad** [comment]
I believe we have figured out the root cause of this issue and a fix will be submitted shortly.

**Comment by shiyuhang0** [comment]
thanks!
