### ISSUE TITLE
Better Error Messages For Unknown Field During Reflection

### ISSUE THREAD

**Issue by ryan-berger** [hashicorp/terraform-plugin-framework#646]
Hello! I'm an infrastructure engineer working at Starbucks on a Terraform provider that we soon plan on open sourcing.  We recently had some cryptic error messages while developing it that I wanted to try adjust to help out Terraform Provider developers in the future.

### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.1.1
```

### Use-cases

During the schema validation phase of a Terraform Plugin, if a type is not an `attr.Value`, the `internal/reflect` package attempts to determine its type via Terraform Plugin type conversion rules. If they don't match up, error messages are emitted. These error messages are important while debugging an author's mistakes.

### Attempted Solutions

To solve this problem, we've had to use `delve` to jump down into the `reflect` package to find out which parts of the schema are causing issues We've also forked the project to provide better error messages for ourselves in case this happens again.

### Proposal

We propose a better message text for the error handled here: https://github.com/hashicorp/terraform-plugin-framework/blob/007a68b1304b659181281e4e4394f67d9256367a/internal/reflect/struct.go#L179

So far, we are only concerned with the following case that is causing a weird error message, but we may find some more while working through our plugin:

When a field exists in a schema but not in a struct (due to a struct tag mismatch or field mismatch) that we're `reflect`ing on, we receive this error message:
```
 couldn't find type information for attribute in supplied attr.Type
        basetypes.ObjectType
```

When working with some nested objects in our schema, this can be hard to deal with.

I propose adding a bit of extra fluff to the error message so that it says:
```
couldn't find type information for attribute <struct property name> at <path>
        in supplied attr.Type <type>
```

I've opened a PR here if this is approved: https://github.com/hashicorp/terraform-plugin-framework/pull/645

Thanks for the awesome product!

**Comment by bflad** [comment]
Hi @ryan-berger 👋 Thank you for raising this! We are generally supportive of trying to make an error messaging clearer where possible.

Real quickly, would you be able show the full Terraform output when the error is generated? We are already passing the attribute path information back to Terraform, which should trigger the output to show a configuration snippet, such as:

```
SEVERITY: SUMMARY

  SNIPPET

DETAIL
```

However we have discovered in certain scenarios where the path information is never shown unless it is manually added to the diagnostic detail (https://github.com/hashicorp/terraform/issues/31575) and it would be nice to get some confirmation that this is another one of those scenarios.

Thanks!

**Comment by ryan-berger** [comment]
I can! I've removed some of the info since the provider isn't quite public yet, and I'm not sure what our policy is. Hopefully this is of use:

```
    xxxxxx_datasource_test.go:9: Step 3/3 error: Error running pre-apply refresh: exit status 1
        
        Error: Value Conversion Error
        
          with data.xxxxxx.test,
          on terraform_plugin_test.tf line 9, in data "xxxxxx" "test":
           9: data "xxxxxx" "test" {
        
        An unexpected error was encountered trying to convert from struct value. This
        is always an error in the provider. Please report the following to the
        provider developer:
        
        couldn't find type information for attribute in supplied attr.Type
        basetypes.ObjectType
```

It definitely does seem like one of those issues!
