### ISSUE TITLE
Float64 - Only whole and half (.5) numbers are accepted, others `cannot be represented as a 64-bit floating point`.

### ISSUE THREAD

**Issue by RobM83** [hashicorp/terraform-plugin-framework#647]
This bug is related or (almost) the same as #613 

### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.1.1
```

### Relevant provider source code

```go
"latitude": schema.Float64Attribute{
	Description:         "Latitude of the resource location",
	MarkdownDescription: "Latitude of the resource location",
	Optional:            true,
},
```

### Terraform Configuration Files

```hcl
latitude  = "123.2"
```

### Expected Behavior

The expected result should be, that floating point numbers like latitude and longitude in this case should be accepted.

### Actual Behavior

Terraform validation fails, when I try to set a value, which is not a “whole” number or a float ending with “.5” So these numbers work (123, 123.5), but all other numbers like (123.1, 123.2, etc.) fail. 

Error message:
```
Error: Value %!s(*big.Float=51.12) cannot be represented as a 64-bit floating point.
```

### References

- #613 

I posted this on the Hashicorp discuss forum as well: 
https://discuss.hashicorp.com/t/terraform-plugin-framework-float64-type-validation-error/48645

**Comment by austinvalle** [comment]
Hey there @RobM83 👋🏻 ! Thanks for raising the bug report and sorry you're still running into this problem. We've continued the bug fix you identified previously-> #613, with another PR that was just merged #648 .

We'll look to release this with our upcoming [1.1.2 release](https://github.com/hashicorp/terraform-plugin-framework/milestone/26)
