### ISSUE TITLE
Add documentation for migrating from `Required` block to new validators

### ISSUE THREAD

**Issue by austinvalle** [hashicorp/terraform-plugin-framework#650]
### Module version

```
v1.1.1
```

### Use-cases

Currently, blocks that are written in SDKv2 can have a `Required` field applied, but there is no equivalent field or validator for `SingleNestedBlock`, `SetNestedBlock`, or `ListNestedBlock`. We are adding validators to solve this issue, but we should document this in our migration guide.

### Proposal

- After creating the new validators, document in: https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-blocks/blocks
- Mention the validators that can be used with each block type as well as plug to not use blocks if possible 😄 

### References
- https://github.com/hashicorp/terraform-plugin-framework-validators/issues/105

**Comment by bflad** [comment]
Now that terraform-plugin-framework-validators v0.10.0 is released with the functionality for this, it may be worth including this as part of #660
