### ISSUE TITLE
Add documentation for RequiredWith migration from SDKv2 to plugin framework

### ISSUE THREAD

**Issue by remyleone** [hashicorp/terraform-plugin-framework#657]
### Module version

```
...
```

**Comment by bflad** [comment]
Hi @remyleone 👋 Thank you for raising this. If you have any specific suggestions, please let us know.

There's currently the [SDK to framework migration guide](https://developer.hashicorp.com/terraform/plugin/framework/migrating), but once it gets to individual `schema.Schema`  fields, the documentation does split up a little bit depending on what you're trying to do. For example with `RequiredWith`, it is mentioned on this migration page: https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-blocks/validators-predefined

But it doesn't say the exact solutions available for that particular field:

- If desired to leave the validation per-attribute, then it is implementing one of the type-specific `AlsoRequires` validators, such as https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework-validators@v0.9.0/stringvalidator#AlsoRequires
- If desired to move the validation to be declared at the resource level, then it is implementing https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework-validators@v0.9.0/stringvalidator#AlsoRequires

@bendbennett do you think we should have https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-blocks/fields and/or https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-blocks/validators-predefined be a little bit more prescriptive about the mapping between the old and new? It may be useful to have tables, such as::

| SDK Attribute Field | Framework Attribute Validator | Framework Resource Validator |
|---|---|---|
| `ConflictsWith` | `{TYPE}validator.ConflictsWith()` | `resourcevalidator.Conflicting()` |

etc.

**Comment by remyleone** [comment]
It would be advantageous to have a table that lists each field and how you should translate it into the framework. I've been looking around many pages to see how I should try out to translate a given pattern. In particular, having a linter tool that offers automated suggestions/helps even if it is very simplistic would help give confidence that it could be achieved. While waiting for an automated tool to appear a table would be very much appreciated and offer great help to map possible migration.

**Comment by bendbennett** [comment]
@bflad I agree that more prescriptive mapping would be useful. To this end I've added an issue for [Add more prescriptive documentation for mapping between SDKv2 and the Framework](https://github.com/hashicorp/terraform-plugin-framework/issues/659#top) and opened a related PR for [Documentation for mapping between SDKv2 and the Framework](https://github.com/hashicorp/terraform-plugin-framework/pull/660#top). I'm happy to expand on this if further, more prescriptive documentation is useful or desired.
