### ISSUE TITLE
Make the documentation clearer about which the different providers in the muxing example

### ISSUE THREAD

**Issue by remyleone** [hashicorp/terraform-plugin-framework#658]
In https://github.com/hashicorp/terraform-plugin-framework/blob/main/website/docs/plugin/framework/migrating/providers/index.mdx#muxing

It would help to have an example that combines an existing provider using SDKv2 and explicitly a new one that says that it is the most recent one. I'm not sure to understand in this example which one is the old one and which one is the new one.

**Comment by bflad** [comment]
Potentially related: https://github.com/hashicorp/terraform-plugin-framework/issues/631
