### ISSUE TITLE
attr.Value.Equal() : *semantically* equal?

### ISSUE THREAD

**Issue by chrismarget** [hashicorp/terraform-plugin-framework#679]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.1.2-0.20230214195151-b784296a0acb
```

While writing tests for [PR 110 for terraform-framework-validators](https://github.com/hashicorp/terraform-plugin-framework-validators/pull/110) I encountered a situation where the `Equal()` method on implementations of `attr.Value` return false when asked to make a comparison with another `attr.Value` with a different underlying type.

Specifically, `z` winds up `false` here:

```go
	x := types.Int64Value(42)
	y := types.NumberValue(big.NewFloat(float64(42)))
	z := x.Equal(y)
``` 

Documentation for `attr.Value.Equal()` uses the term *semantically equal*, which suggests to me that `z` should wind up `true` in the snippet above.

```go
type Value interface {
	// Equal must return true if the Value is considered semantically equal
	// to the Value passed as an argument.
	Equal(Value) bool
```

Maybe I've misunderstood?

I was going to raise this question in the conversation about the validator PR, but thought it better to address it separately.

At this point, I'm not sure whether we're talking about (a) confusion on my part (b) implementation bugs in `Equal()` or (c) a documentation bug in the `Value` interface.

In any event, clarifying this (apparent?) discrepancy should drive the answer to the test failure I mentioned in the conversation about the validator PR.

Thanks!

**Comment by bflad** [comment]
Hi @chrismarget 👋 Thank you for raising this -- real briefly, technically that documentation should read _syntactically_ and type equal. #70 represents a future enhancement to support _semantic_ equality, but that equality would still be limited to the same type. Once going beyond the definition of equality past the same type, equality becomes harder to define. There are a few potential cases where two separate values of numbers (Float64, Int64, Number), scalar collections (List, Set, and to a certain degree tuples with consistent value types), and nested value collections (Map, Object) could effectively represent the same data to a human. I think if we were to attempt to support that concept in the framework type system, it would require some use case and design consideration.

**Comment by chrismarget-j** [comment]
Hi @bflad,

> that documentation should read syntactically and type equal

Cool. I can proceed with that understanding. If you'd like me to help with an edit to the documentation, I'm happy to do so, but I won't be proactive about opening that PR unless you request it.

> enhancement to support semantic equality, but that equality would still be limited to the same type

I don't understand the distinction here. What does it mean to say that two values of the same type are *semantically* equal?

> I think if we were to attempt to support...

In case it's not clear, I'm *not asking* for `attr.Value.Equal()` to support meaningful equality evaluation between different types, and I appreciate that it would be a big effort. I just believed that it did support that sort of comparison, wrote tests with that understanding in mind, and then ran into a wall when the tests failed.

Amending my tests to reflect the intended behavior (based on your comment here) is good enough for me.

**Comment by bflad** [comment]
> If you'd like me to help with an edit to the documentation, I'm happy to do so, but I won't be proactive about opening that PR unless you request it.

You're welcome to submit that change, if you're willing. The current documentation is technically incorrect so fixing it is work that someone would need to address.

> What does it mean to say that two values of the same type are semantically equal?

Terraform maintainers sometimes refer to _syntactic_ equality as byte-wise or exact equality whereas _semantic_ equality is a functionality equivalent form of the same data. Some canonical use cases for semantic equality are the difference between two string values:

- Case-sensitivity: A remote system may accept lowercase or uppercase characters, but always represent them in one form.
- JSON encoded data: The JSON specification says that object properties are unordered and that whitespace is generally insignificant.

These use cases break Terraform's data value consistency rules, which are based on exact equality. If the remote system may work with fuzzier values and practitioners expect to work with those fuzzier values, it is important for providers to smooth over the difference. In general, this means providers should not suggest differences for in-exact values that are semantically equivalent (generally by discarding a proposed new state if it is semantically equivalent of the configuration or prior state).
