### ISSUE TITLE
Support per-resource, per-operation timeouts

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-framework#68]
### Module version

```console
% go list -m github.com/hashicorp/terraform-plugin-framework/...
github.com/hashicorp/terraform-plugin-framework v0.1.0
```

It will be necessary to support [per-resource, per-operation timeouts](https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts).

**Comment by paddycarver** [comment]
Possibly a duplicate of #62.

**Comment by ewbankkit** [comment]
Yes it is - I thought that the underlying Terraform protocol had special knowledge of the `timeouts` block but it seems that this is provider-side functionality.
