### ISSUE TITLE
Classifying normalization vs. drift

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform-plugin-framework#70]
(I originally wrote up a longer version of this which included a lot more background information and historical context, but then when I submitted it GitHub encountered an error and lost my content. Sadly I don't have time to reproduce what had been 45 minutes of research and writing and so I'm resorting to a more direct description of a problem in the hope that readers will be familiar enough with this problem to realize what I'm talking about without the background information. However, I'm happy to answer any clarifying questions if the context is unclear here.)

An important responsibility of a provider is to classify whether a difference between two values represents drift (a material change in meaning often -- but not always -- caused by edits made outside of Terraform) or normalization (a different way of writing down the same thing).

In the old SDK we had `DiffSuppressFunc` as the primary solution to this problem. On a per-attribute basis this function would take two values and return `true` if they are functionally equivalent or `false` if they are materially different.

Unfortunately, the implementation of `DiffSuppressFunc` was applied only during `PlanResourceChange` and not during `ReadResource`, which sadly only solves half of the problem and thus largely defeats the benefit of the mechanism.

We can see a concrete example of that in hashicorp/terraform#29181, where the provider seems to have classified a reordering of a JSON array as normalization rather than as drift, but because the SDK didn't check `DiffSuppressFunc` on the `Read` response the normalized value was misclassified as a material change.

Although the recent "Objects have changed outside of Terraform" message has made this sort of incorrect result more visible, note that it's still a potential problem regardless of whether Terraform explicitly reports it because Terraform allows using the value of an argument of one resource to populate an argument of another resource. For example:

```hcl
resource "happycloud_thingy" "foo" {
  name = "Hello"
}

resource "monitorsauce_doodad" "bar" {
  title = "Statistics for ${happycloud_thing.foo.name}"
}
```

If this "HappyCloud" vendor has an API which normalizes thingy names to lowercase, then we'd likely want to classify case changes as normalization vs. drift. If `ReadResource` were to set `name` to `hello` rather than `Hello` then a subsequent plan could propose the following, even though `PlanResourceChange` for `happycloud_thingy` classified the name change as normalization:

```
  # monitorsauce_doodad.bar must be replaced
-/+ resource "monitorsauce_doodad" "bar" {
     ~ title = "Statistics for Hello" -> "Statistics for hello" (forces replacement)
    }
```

In modern Terraform the "Objects have changed outside of Terraform" message would at least give a clue as to why this happened, but it'd be better if Terraform had just reported no changes needed at all, thus allowing the configuration to properly converge in only one plan/apply run.

As far as I can tell this new framework doesn't yet have a comparable feature to `DiffSuppressFunc` at all, and so my purpose in opening this issue is mainly just to capture this background information (albeit a cut down version due to the work loss mentioned earlier) in the hope that it's useful for designing any feature that might meet a similar need.

I'd also assert, though others might disagree, that this normalization vs. drift problem is a crucial enough part of a provider's responsibility to get right that it would be warranted to have first-class framework support for it, such that it can work correctly by default and thus hopefully avoid the risk of individual resource implementations effectively repeating the old SDK's mistake of only solving half of the problem. :confounded:

**Comment by paddycarver** [comment]
This may be related to #34 / #64, or an abstraction on top of them? Perhaps we could have ReadModifiers similar to PlanModifiers? We could also try and combine the two concepts into one, though I'm nervous about how the presence/absence of a config/plan (present in PlanResourceChange, absent in ReadResource) may impact the leakiness of that abstraction.

**Comment by apparentlymart** [comment]
I guess my hypothesis here was that the most robust thing would be for the framework to offer something that makes consistency between `ReadResource` and `PlanResourceChange` the _default_ behavior, because them having different rules for classifying these (or, in the extreme case, not having any normalization detection in the `ReadResource` case at all) seems more likely to be a mistake than an intentional decision.

However, I do admit that it's hard to back that up with real data since we've not ever _had_ an SDK which handled this consistently, and so we only have the current not-quite-right case and thus the grass naturally seems greener on the other side. There might be some hidden use-cases for intentionally making these divergent which are currently not visible because they "just work" without any special effort in the current SDK.

If we were designing the old SDK's `DiffSuppressFunc` as a new feature today then I would've proposed it be run automatically 
by the SDK also during `ReadResource` in order to get the intended effect, but I know this new framework is aiming to make some different design tradeoffs so I expected that lifting that feature exactly as-is wouldn't be the ideal approach, and hence this rather vague issue just gesturing at a problem but without a concrete solution. :confused: 

With that said, I can at least try to frame the _problem_ more concretely in old SDK terms, so we have something specific to compare with: for the old SDK design, I'd propose to have the `ReadResource` part of the SDK first call the provider's `Read` function, having the provider call `d.Set` to update everything to match the remote system, and then _afterwards_ to call `DiffSuppressFunc` on every attribute the `Read` function had changed in order to compare the original value (prior to `Read`) with the new value (set inside `Read`). If `DiffSuppressFunc` returns `true`, then reset the value back to the original because the detected change was classified as normalization, rather than as drift.

I'm not sure how to generalize that to the broader concern of "plan customization" because there are various other use-cases for plan customization that _aren't_ related to normalization/drift classification and which, as you point out, would make sense to only run during the planning step and not during the refreshing step. For example, the classic `CustomizeDiff` use-case of "if you change the content of `s3_bucket_object` then the `version` attribute should be unknown in the plan"; I can't find any analog for that rule in the `ReadResource` step, because we already know concretely what the new version number is in that case.

**Comment by apparentlymart** [comment]
I ended up thinking about this some more today because I encountered another situation where a normalization change ended up propagating downstream and generating a confusing result. I've felt bad about just showing up here with a problem statement and not making any particular suggestions on what to do about it, so I had a look again at the framework design so far (looks like it's coming together well!) and noticed some hooks that seem promising to me as parts of a potential solution to the problem I've raised here, and wanted to note them. Perhaps you all already had this in mind when you designed these things and I'm just telling you things you already know :grinning: but can't hurt to write it out here anyway, for future reference.

## `attr.Value`

The main thing I learned about today that I hadn't previously seen is [`attr.Value`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework@v0.2.0/attr#Value) as a higher-level a abstraction over the physical types in Terraform's type system. Adding a new concept in between the idea of an attribute and the physical type of that attribute seems like a great insight that I hadn't previously considered, and seems like it'll give a lot of opportunities for handling cross-cutting concerns in typical providers!

The `Equal` method that you've already defined for `Value` reads to me as, semantically if not behaviorally, the new-framework equivalent of `DiffSuppressFunc` in the old SDK, assuming I'm correctly understanding the intent that it should return `true` if two values are functionally equivalent per the definition of the specific type in question. For example, I'm thinking about a hypothetical `Value` implementation representing a case-insensitive string, where `Equal` would return true if both values have the same sequence of letters even if their case disagrees in a way that the remote API doesn't care to distinguish.

## Potential automatic Read/Plan/Apply response tidying

The other thing I saw on my travels is that there seems to be some precedent in the `PlanResourceChange` implementation for some automatic behavior (that is, behavior implemented for all providers in the framework rather than in the provider code itself), currently involving fitting in all of the necessary unknown values into the attributes that won't be decided until the apply step:

https://github.com/hashicorp/terraform-plugin-framework/blob/b61fdeb9f9936a995ec85546d724f4b724c4d3cd/tfsdk/serve.go#L437-L445

This got me thinking about a possible additional transform step which takes an object representing the prior state along with the resource type schema. For each leaf attribute it visits, it could perhaps raise the two `tftypes` values representing the value that was given to transform and the corresponding value from the prior state into `schema.Value`, call `Value.Equal` with them, and then use the result to decide between returning the prior value (if `Equal` returns `true`) or the new value (if it returns `false`).

To get the effect I was hoping for when I opened this, I think we'd need to then call this function _at least_ in both `PlanResourceChange` and in `ReadResource`, so that both of them will always prefer to preserve an existing value rather than switching to a functionally-equivalent value that Terraform Core would not consider as equal.

I also wonder about doing it in `ApplyResourceChange` in order to keep the planned value if the final value is functionally equivalent to it, for consistency's sake, though that would have a different benefit than the one I opened this issue about: it would help provider developers getting tripped up by the "Provider produced inconsistent result after apply" safety check, by automatically preserving exactly the value that was in the plan as long as the final result was functionally equivalent to it.

---

I don't have nearly enough context to consider any of this to be a proper design proposal... more just some initial ideas to hopefully better explain the sort of thing I was imagining when I opened this issue. I hope it's useful in some way! Please let me know if anything here seems surprising or weird; I'm still very early in learning my way around the framework so I wouldn't be surprised or offended to hear that I misunderstood something in this initial exploration of the problem.

With that said, if this looks like a promising direction and you'd be _open_ to outside input then I'd be happy to try to do some more of the legwork to turn this into a more proper design proposal, though I would need to wait a little while to first work through some other tasks since our team is stretched a bit thin right now.

**Comment by apparentlymart** [comment]
To satisfy my curiosity I made an attempt at implementing something like what I described in the previous comment, over in #178.

For the moment I'm offering that mainly just as something to play with to see the effect of the design I was considering. If it seems promising then I'd be happy to produce a more complete design proposal before getting into the weeds of how exactly I implemented that, since I expect I didn't do it in the best way due to my unfamiliarity with this codebase.

**Comment by YakDriver** [comment]
I've found 3 places where normalization/equivalence vs. drift/meaningful changes affects the AWS provider. As for impact, we have approximately 11 open issues with a combined 400 upvotes that relate to the problem.

### 1. Create/Config Update

This is the situation that is handled with `DiffSuppressFunc` at present by something like `verify.SuppressEquivalentPolicyDiffs()`.

### 2. Read/Set - Drift Detection

This situation is not well handled currently but can be intercepted to check equivalence before `d.Set()`.

### 3. `ImportStateVerify`

We can write a custom check but, again, it would be helpful to have this comparison have an option for equivalence.

**Comment by apparentlymart** [comment]
Hi @YakDriver! Thanks for sharing that extra context.

I must admit I hadn't really considered the case of importing. I'm rusty on the legacy SDK and so I don't remember exactly how `ImportStateVerify` fits in, and so maybe this is not a relevant observation, but I feel that our current model of import is a bit challenging with regard to normalization vs. drift because in that case we're constructing an entirely new state object from something essentially equivalent to a "read" call, and so we don't have anything to compare with in order to decide which value should "win".

If you have some examples to hand of import-related problems _in particular_ then I'd love to learn about them to fold them into my understanding of how that contributes, since my investigation so far has focused only on the read, plan, and apply steps.

**Comment by YakDriver** [comment]
@apparentlymart `ImportStateVerify` is definitely not our primary concern. See my comment above where I've amplified. Also, I've found that by using `jsonencode()` and being careful, I can problems. It does involve rewriting test configurations to make sure they're seen as equivalent even if they were already equivalent but not seen as such. It's a burden I'd prefer the community to not have but, like I said, not top priority.

Here's an example that will not pass `ImportStateVerify`.

```terraform
resource "aws_kms_key" "test" {
   description             = "don_key"
   deletion_window_in_days = 7

   policy = <<POLICY
 {
   "Version": "2012-10-17",
   "Id": "kms-tf-1",
   "Statement": [
     {
       "Sid": "Enable IAM User Permissions",
       "Effect": "Allow",
       "Principal": {
         "AWS": "*"
       },
       "Action": "kms:*",
       "Resource": "*"
     }
   ]
 }
 POLICY
}
```

However, if we switch to `jsonencode()`, `ImportStateVerify` will see the equivalent JSON _as equivalent_:
```terraform
resource "aws_kms_key" "test" {
   description             = "don-key"
   deletion_window_in_days = 7

  policy = jsonencode({
     Id        = %[1]q
     Statement = [{
       Sid       = "Enable IAM User Permissions"
       Effect    = "Allow"
       Principal = {
         AWS = "*"
       }
       Action   = "kms:*"
       Resource = "*"
     }]
     Version = "2012-10-17"
   })
 }
```

**Comment by apparentlymart** [comment]
Ahh, I went to look in the SDK repository to remind myself what `ImportStateVerify` is and now remember that it's part of the test framework rather than part of the runtime code. Sorry for misunderstanding what you were talking about there! I can see where there is some conceptual overlap with the normalization vs. drift problem there though, because the test harness is trying to verify that the state objects generated during import are "equal" to some original state.

I'm not really sure what is the equivalent functionality to that in the new framework right now, but I'll use this comment as a reminder to research that some more later to see if something to address that might be in scope for the proposal I've been working towards (intermittently) here.

**Comment by bflad** [comment]
This new framework does not implement acceptance testing features. A separate, new acceptance testing framework is being planned instead. I'd ensure there is a covering issue back in https://github.com/hashicorp/terraform-plugin-sdk/issues to cover `ImportStateVerify` and state equality in the meantime, if nothing else, to remind us to think about that issue during that design.

**Comment by apparentlymart** [comment]
I was focusing on understanding what role `ImportStateVerify` was playing in my comments above but also want to acknowledge that indeed complex data structures represented as JSON are a definite pain point for Terraform diffing _in general_ (both for reporting drift and for showing what action is planned).

It's a tricky case where we've given Terraform CLI no information about the expected data structure -- it just knows that it's a string, and can detect heuristically that the string contains JSON -- and so CLI doesn't really have any option but to be conservative and assume that the ordering of arrays matters, because for JSON alone (without any information about the higher-level language built on top of it) array order _is_ defined as being significant.

Unless we want to switch to describing the expected shape of an IAM policy using Terraform's type system in the schema, I think that will end up being a rough edge that this issue alone probably won't be able to solve. There might be some more involved designs we could think about, such as some way to explicitly hint in schema that a string is supposed to contain JSON _and_ that parts of it have arrays that represent sets, but I wouldn't want to delay solving the more straightforward cases in order to comprehensively address that particularly gnarly case.

With that said, I think there _would_ be a path to addressing this within the constraints of what I was beginning to propose here, but it would be one that would require a partnership between general SDK logic and provider-specific logic. Specifically, when performing the `ReadResource` operation for something containing an IAM policy, rather than just returning the remote policy JSON verbatim and letting the `Equal` function decide normalization vs. drift the provider would need to deeply analyze the before and after policy JSON itself and have an algorithm to merge the new into the old in a way that preserves the relative ordering of any unchanged elements in "set-like" arrays, and thus the UI-level diff renderer's [LCS algorithm](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem) should _typically_ be able to show just the additions and removals.

With that said, I'm mentioning that only for completeness here and not necessarily recommending implementing something like that: it's a much more complex analysis than we've traditionally required here, and so I'd ultimately leave the decision to the AWS provider team about whether it's worth implementing something like that to address the immediate problems with policy diffs, given that we don't currently have any defined path to a framework-only or CLI-only solution for that particular awkward case.

**Comment by YakDriver** [comment]
Thank you @apparentlymart and @bflad for the comments and thought on this!! It's helped a lot in thinking about it.

For now, our approach will be to solve the `Read` situation with a little helper in the provider. Since many of our outstanding issues convolute the messy real diffs and perpetual diffs, it's difficult to tell how much pain comes from each. After fixing this part, we can reassess what level of pain remains.

If needed, I would not be opposed to a `TypeJSON` to allow more specific handling. Depending on the results of the first round of fixes, we may want to test out the concept in the AWS provider and if it goes well, promote the idea up.

**Comment by bflad** [comment]
We still need to setup a broader discussion on this topic internally, but to quickly document another potential proposal we could noodle on is adding a "semantic equals" interface to the type system for values, then using that new, optional interface to automatically normalize values after any provider-defined plan/state writing has occurred (similar to #178). This ensures that value types can still distinguish between fully equal values (e.g. syntax, byte-for-byte, etc.) and any semantically equal values (e.g. different representations). Provider developers could then opt into this framework behavior, if desired for their use cases.

As a quick sketch:

```go
package attr

type ValueWithSemanticEquals interface {
  Value

  // SemanticEquals should return true if the given Value is
  // semantically equal (e.g. another valid representation) of
  // the Value.
  SemanticEquals(Value) bool
}
```

Where the framework logic will then check for this prior to returning a RPC response, such as:

```go
package fwserver

func (s *Server) CreateResource(ctx context.Context, req *CreateResourceRequest, resp *CreateResourceResponse) {
	// ...

	// Example normalization logic that goes through the Values and
 	// if the schema type implements attr.TypeWithSemanticEquals and
	// returns true, it will replace the new value with the old value.
	normalize(ctx, req.PlannedState, resp.NewState)
}

func (s *Server) PlanResourceChange(ctx context.Context, req *PlanResourceChangeRequest, resp *PlanResourceChangeResponse) {
	// ...

	// Example normalization logic that goes through the Values and
 	// if the schema type implements attr.TypeWithSemanticEquals and
	// returns true, it will replace the new value with the old value.
	normalize(ctx, req.PriorState, resp.ProposedNewState)
}

func (s *Server) ReadResource(ctx context.Context, req *ReadResourceRequest, resp *ReadResourceReponse) {
	// ...

	// Example normalization logic that goes through the Values and
 	// if the schema type implements attr.TypeWithSemanticEquals and
	// returns true, it will replace the new value with the old value.
	normalize(ctx, req.State, resp.NewState)
}

func (s *Server) UpdateResource(ctx context.Context, req *UpdateResourceRequest, resp *UpdateResourceResponse) {
	// ...

	// Example normalization logic that goes through the Values and
 	// if the schema type implements attr.TypeWithSemanticEquals and
	// returns true, it will replace the new value with the old value.
	normalize(ctx, req.PlannedState, resp.NewState)
}
```

If providers want to opt out of the behavior and begin returning these differences, they can change which schema type is being used (e.g. "JSON string type" to types.String or another type), or adjust/remote the type's `SemanticEquals()` method if it is under their control.

There's also nothing in the way of using `UpgradeResourceState` to transparently update the state regardless of the type implementation. I think this should be purposefully excluded from that RPC handling so provider developers can choose whether to preserve prior normalization or not.

This `SemanticEquals()` method would then be something that a theoretical "JSON string" type could implement to handle whitespace and unordered property differences, for example. I think this may strike a nice balance between "automatically doing the right thing" if you implement specialized types while still leaving it opt-in.
