### ISSUE TITLE
Dead link in migration benefits/"Framework and SDKv2 Feature Comparison" page

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-plugin-framework#734]
Hi DevEx 👋 

I encountered a [dead link](https://developer.hashicorp.com/terraform/plugin/framework/migrating/benefits#null-unknown-and-known-values) in the plugin framework documentation - the heading used for the link below isn't present on the page:

https://github.com/hashicorp/terraform-plugin-framework/blob/054cfaad20336748da52bb63053091c511ba5ea9/website/docs/plugin/framework/migrating/benefits.mdx?plain=1#L126

I think that it's meant to be linking to this section? : https://developer.hashicorp.com/terraform/plugin/framework/migrating/benefits#fully-exposed-value-states

I'm not certain though, and because the fix needs more than just a change to the URL value I'm opening an issue instead of a PR.

**Comment by bflad** [comment]
Hey @SarahFrench 👋 Thanks for raising this -- indeed that anchor link should be pointing at the current "Fully Exposed Value States" header instead of that older wording of it. We would be happy to accept a PR from you or anyone else wanting to fix it. 👍
