### ISSUE TITLE
Plan Modifiers Doesn't Work with Custom String Type

### ISSUE THREAD

**Issue by zliang-akamai** [hashicorp/terraform-plugin-framework#754]
### Module version

```
v1.3
```

### Relevant provider source code

```go

var frameworkResourceSchema = schema.Schema{
	Attributes: map[string]schema.Attribute{
		"expiry": schema.StringAttribute{
			Description: "When this token will expire. Personal Access Tokens cannot be renewed, so after " +
				"this time the token will be completely unusable and a new token will need to be generated. Tokens " +
				"may be created with 'null' as their expiry and will never expire unless revoked. Format: " +
				helper.TIME_FORMAT,
			Optional: true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplaceIf(
					func(
						ctx context.Context,
						sr planmodifier.StringRequest,
						rrifr *stringplanmodifier.RequiresReplaceIfFuncResponse,
					) {
						rrifr.RequiresReplace = !helper.CompareTimeStrings(
							sr.PlanValue.ValueString(),
							sr.StateValue.ValueString(),
							time.RFC3339,
						)
					},
					RequireReplacementWhenScopesChangedDescription,
					RequireReplacementWhenScopesChangedDescription,
				),
			},
			Validators: []validator.String{
				helper.NewDateTimeStringValidator(time.RFC3339),
			},
			CustomType: customtypes.RFC3339TimeStringType{},
		},
		"created": schema.StringAttribute{
			Description: "The date and time this token was created.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
			CustomType: customtypes.RFC3339TimeStringType{},
		},
		// ... other attrs
	},
}

```

### Terraform Configuration Files

```hcl
resource "linode_token" "foo" {
  scopes = "linodes:read_only"
  expiry = "2030-01-02T04:04:05+01:00"
}
```

### Expected Behavior
Successfully apply the configuration to the cloud.

### Actual Behavior
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Value Conversion Error
│ 
│   with linode_token.foo,
│   on main.tf line 16, in resource "linode_token" "foo":
│   16:   expiry = "2030-01-02T04:04:05Z"
│ 
│ An unexpected error was encountered while verifying an attribute value matched its expected type to prevent unexpected behavior or panics. This is always an error in the provider. Please
│ report the following to the provider developer:
│ 
│ Expected type: RFC3339TimeStringType
│ Value type: basetypes.StringType
│ Path: expiry
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Custom type

The example from the docs, https://developer.hashicorp.com/terraform/plugin/framework/handling-data/custom-types

**Comment by bflad** [comment]
Hi @zliang-akamai 👋 Thank you for raising this and sorry you ran into trouble here.

When implementing a custom type, it is important that all values are created with the [value type associated with the schema type](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/custom-types#developing-custom-types). For example, the framework's `basetypes.StringType` is associated with `basetypes.StringValue` while in your case the `customtypes.RFC3339TimeStringType{}` should be associated with its own custom Go type for values and not `basetypes.StringValue`. If you're extending the framework base type via Go's type embedding functionality, the expectation is that you would return any values using the custom value type as a wrapper, not directly via something like `types.StringValue()`.

Can you confirm that all references in your resource logic and data models are using the value type associated with `customtypes.RFC3339TimeStringType{}` and any value creation happens either with or through that value type?

**Comment by zliang-akamai** [comment]
Hey @bflad, thanks for the response!

We uses the model for returning values, similar to the recommendation from the docs.

```go
type ResourceModel struct {
	Expiry  customtypes.RFC3339TimeStringValue `tfsdk:"expiry"`
	Created customtypes.RFC3339TimeStringValue `tfsdk:"created"`
	ID      types.String                       `tfsdk:"id"`
	// some other fields...
}
```

```go
m.Created = customtypes.RFC3339TimeStringValue{
	StringValue: types.StringValue(token.Created.Format(time.RFC3339)),
}
```

```go
resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
```

So I am pretty sure the provider response code didn't cause the issue.

I think the issue is in the framework built in plan modifier `planmodifier.String`. We used to use the modifiers in this package for our attributes in the schema, but they doesn't work with the custom type which extends built-in framework built-in base types.

And I feel it would be nicer if these built-in modifier can works with the custom type which extends built-in framework built-in base types. BTW, may I know if you were able to reproduce the issue?

**Comment by bflad** [comment]
Hi @zliang-akamai 👋 Thank you for the followup. Using attribute-based plan modification should not trigger this type of error, however it appears there is some framework logic missing to prevent the error. I will be taking a look to resolve it.

**Comment by bflad** [comment]
terraform-plugin-framework v1.3.1 has been released with the fix for this. Please reach out if you have any issues after upgrading the dependency and thanks again for the bug report.
