### ISSUE TITLE
Custom Type with StringSemanticEquals not working as expected

### ISSUE THREAD

**Issue by carlosjourdan** [hashicorp/terraform-plugin-framework#786]
Hello everyone. 

I'm trying to create o Custom Type to handle generic json attributes, using the StringSemanticEquals interface to ignore any inconsequential changes to the json text representation (e.g. attribute ordering or whitespaces), but things are not working as I would expect by reading the docs.

I must admit I have zero experience in plugin development or even golang itself, so apologies in advance if I'm making any silly mistakes.

### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.3.1
```

### Relevant provider source code

```go

package customtypes

import (
	"context"
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

var (
	_ = basetypes.StringValuable(&JsonValue{})
	_ = basetypes.StringValuableWithSemanticEquals(&JsonValue{})
	_ = fmt.Stringer(&JsonValue{})
)

// JsonValue implements a custom Terraform value that represents
// a JSON string with semantic equality
type JsonValue struct {
	basetypes.StringValue
}

// NewJsonNull creates a Json with a null value. Determine
// whether the value is null via the JsonType IsNull method.
func NewJsonNull() JsonValue {
	return JsonValue{
		StringValue: basetypes.NewStringNull(),
	}
}

// NewJsonUnknown creates a Json with an unknown value.
// Determine whether the value is null via the JsonType IsNull
// method.
func NewJsonUnknown() JsonValue {
	return JsonValue{
		StringValue: basetypes.NewStringUnknown(),
	}
}

// NewJsonValue creates a Json with a known value. Access
// the value via the JsonValue type ValueString method.
func NewJsonValue(value string) JsonValue {
	var stringValue basetypes.StringValue

	if len(value) > 0 {
		stringValue = basetypes.NewStringValue(value)
	} else {
		stringValue = basetypes.NewStringNull()
	}

	return JsonValue{
		StringValue: stringValue,
	}
}

// NewJsonPointerValue creates a Json with a null value if
// nil or a known value. Access the value via the JsonValue type
// ValueStringPointer method.
func NewJsonPointerValue(value *string) JsonValue {
	if value == nil {
		return NewJsonNull()
	}

	return NewJsonValue(*value)
}

// Equal returns true if this json is equal to o.
func (v JsonValue) Equal(o attr.Value) bool {
	other, ok := o.(JsonValue)
	if !ok {
		return false
	}

	result, err := JSONEqual(v.ValueString(), other.ValueString())

	if err != nil {
		return false
	}

	return result
}

// Type returns an instance of the type.
//
//nolint:ireturn // required to implement StringValuable
func (v JsonValue) Type(_ context.Context) attr.Type {
	return JsonType{}
}

// StringSemanticEquals checks if two JsonValue objects have
// equivalent values, even if they are not equal.
func (v JsonValue) StringSemanticEquals(_ context.Context, newValuable basetypes.StringValuable) (bool, diag.Diagnostics) {
	var diags diag.Diagnostics

	newValue, ok := newValuable.(JsonValue)
	if !ok {
		diags.AddError(
			"Semantic Equality Check Error",
			fmt.Sprintf("Expected value type %T but got value type %T. Please report this to the provider developers.", v, newValuable),
		)

		return false, diags
	}

	result, err := JSONEqual(newValue.ValueString(), v.ValueString())

	if err != nil {
		diags.AddError(
			"Semantic Equality Check Error",
			err.Error(),
		)

		return false, diags
	}

	return result, diags
}

func JSONBytesEqual(a, b []byte) (bool, error) {
	var j, j2 interface{}
	if err := json.Unmarshal(a, &j); err != nil {
		return false, err
	}
	if err := json.Unmarshal(b, &j2); err != nil {
		return false, err
	}
	return reflect.DeepEqual(j2, j), nil
}

func JSONEqual(a, b string) (bool, error) {
	return JSONBytesEqual([]byte(a), []byte(b))
}


```

### Terraform Configuration Files

```hcl
resource "my_custom_resource" "name" {
    some_json_type_attribute = "{\"attr2\": \"value2\", \"attr1\": \"value1\"}"    
}
```

### Expected Behavior

1. Upon resource creation, backend replies with the json with a different order in the attributes. I return a model that has a JSonValue attribute which is both "Equal" and "StringSemanticEquals" to the prior value. I would expect terraform to accept this as inconsequential.
2. When the user makes an inconsequential change to the .tf file (e.g. adding whitespace to the string definition) I would expect terraform to ignore this and not propose an update

### Actual Behavior

1. Terraform displays the following error: 
```
When applying changes to my_custom_resource.name, provider "provider[\"myprovider"]" produced an unexpected new value:
│ .some_json_type_attribute : was cty.StringVal("{\"attr2\": \"value2\", \"attr1\": \"value1\"}"), but now
│ cty.StringVal("{\"attr1\": \"value1\", \"attr2\": \"value2\"}").
```

2.Terraform proposes a resource update when the .tf has an inconsequential change

**Comment by austinvalle** [comment]
Hi there @carlosjourdan 👋🏻 , thanks for opening the issue and sorry you're running into this problem!

Looking at the code snippet and error message provided, you're running into a data consistency problem caused by the `Equal` method implementation below:

```go
func (v JsonValue) Equal(o attr.Value) bool {
	other, ok := o.(JsonValue)
	if !ok {
		return false
	}

	result, err := JSONEqual(v.ValueString(), other.ValueString())

	if err != nil {
		return false
	}

	return result
}
```

The `Equal` method differs from the `StringSemanticEquals` method in that:
- `Equal` should return `true` if the type and value are equal as defined by **Terraform's data consistency rules**
   - For a string, runes are compared byte-wise (so two JSON strings with different order/whitespace, are not equal)
- `StringSemanticEquals` should return `true` if the type and value are equal as defined by **your own custom rules**, which you have correctly implemented here for two JSON strings being equal

To fix your issue, you can update your `Equal` method to the following code:
```go
func (v JsonValue) Equal(o attr.Value) bool {
	other, ok := o.(JsonValue)

	if !ok {
		return false
	}

	return v.StringValue.Equal(other.StringValue)
}
```

I will be updating our [documentation for Custom Types](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/custom-types#value-type) to make this distinction between `Equal` and `{Type}SemanticEquals` clearer.

As an aside, my team is currently working on new custom type Go modules that should include something like `jsontypes.NormalizedString` to solve this exact use-case you're running into now.

Please keep an eye on this issue I opened to track the implementation: https://github.com/hashicorp/terraform-plugin-framework/issues/803

**Comment by austinvalle** [comment]
The documentation has been updated to provide clarity about this behavior. In addition, [three new Go modules have been released](https://github.com/hashicorp/terraform-plugin-framework/issues/803#issuecomment-1662428339) with custom type implementations that you could use as a reference for building your own.

From your description of the JSON type behavior you were looking to achieve, I believe the newly released [`jsontypes.NormalizedType`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework-jsontypes@v0.1.0/jsontypes#NormalizedType) and [`jsontypes.Normalized`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework-jsontypes@v0.1.0/jsontypes#Normalized) (value) would fit what you're looking for. If you run into any issues with these types you can file a bug report in the [related repository](https://github.com/hashicorp/terraform-plugin-framework-jsontypes).

Thanks! 👋🏻

**Comment by carlosjourdan** [comment]
Thank you very much! The new json types are exactly what I was building, it's great to be able to migrate to an already built package.
