### ISSUE TITLE
Cannot skip the ImportState method implementation as described

### ISSUE THREAD

**Issue by a146518** [hashicorp/terraform-plugin-framework#796]
https://github.com/hashicorp/terraform-plugin-framework/blob/e036d9fbab4b72f8ec671a9d3e94649040e3eeb5/website/docs/plugin/framework/resources/import.mdx#L88

The documentation states that we can skip the ImportState method implementation if the provider will not support it. However, upon removing the method implementation you get an error

*someResource does not implement "github.com/hashicorp/terraform-plugin-framework/resource".ResourceWithImportState (missing ImportState method)

**Comment by a146518** [comment]
You are correct I still had that in my implementation.

Is it possible to write an acceptance test to assert that we get the expected behavior with ImportState when ImportState is specifically not implemented?

Something like:
```
			{
				ResourceName:      "someResource.resourceName",
				ImportState:       true,
				ImportStateNotImplemented: true,
			},
```

So that it is explicit about not implementing import in testing?

Thanks

**Comment by bflad** [comment]
@a146518 if that type of testing coverage is important for you, please raise a feature request in https://github.com/hashicorp/terraform-plugin-testing/issues, which is where the provider testing code is implemented. Please note though that [implementing resource import is considered best practice for provider design](https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles#resources-should-be-importable).

**Comment by bflad** [comment]
@a146518 do you need anything else with this issue?

**Comment by a146518** [comment]
This is resolved after following the @bendbennett suggestion. Thanks
