### ISSUE TITLE
Document required id field for testing

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#80]
Providers that want to run acceptance tests using `helper/resource` need to have an `id` attribute set on them, or they'll get the following errors:

```
    testing_new_config.go:111: no "id" found in attributes
    testing_new.go:53: no "id" found in attributes
```

We should document this requirement on https://www.terraform.io/docs/plugin/framework/acctests.html so provider developers don't need to figure it out the hard way.

**Comment by bflad** [comment]
This also came up for a developer using terraform-plugin-go as well. Not saying anything additional needs to be done, but leaving that breadcrumb for additional context.

**Comment by phact** [comment]
I'm hitting this today when trying to test a `datasource`. What is it that needs an ID? Is it the `helper/resource`? How do I give it an `id`?
Interestingly when I test my `resources` they work fine. Here's my dump:

```
    testing_new_config.go:72: no "id" found in attributes
    testing_new.go:49: no "id" found in attributes
```

**Comment by paddycarver** [comment]
Your data source needs to have an attribute named "id". :)

**Comment by kmoe** [comment]
How about adding something to the error message saying that an `id` field is currently required for testing, but doesn't affect anything else?

**Comment by paddycarver** [comment]
Yeah, I'd be in favor of that. Maybe removing the repetition of the error, too.
