### ISSUE TITLE
Floating point precision differences after migrating from SDKv2

### ISSUE THREAD

**Issue by jharley** [hashicorp/terraform-plugin-framework#815]
I recently migrated the `honeycombio_trigger` resource from the Plugin SDKv2 to the Plugin Framework and received a bug report that the way floating point numbers are being handled is differently.

I think this is not so much a 'bug' -- I can see increased precision as a feature! -- but I am looking for guidance on how to handle this case. A custom `planmodifier`?

### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.3.3
```

### Relevant provider source code

https://github.com/honeycombio/terraform-provider-honeycombio/blob/main/internal/provider/trigger_resource.go#L132-L153

### Terraform Configuration Files

```hcl
data "honeycombio_query_specification" "test" {
  calculation {
    op     = "COUNT"
  }

  time_range = 1200
}

resource "honeycombio_trigger" "test" {
  name = "floating point test"

  dataset  = var.dataset
  query_id = data.honeycombio_query_specification.test.id

  threshold {
    op    = ">"
    value = 1 - 0.99
  }
}
```

### Debug Output

https://gist.github.com/jharley/90ec9c38c70858c0e1bdcaaea0707c05

### Expected Behavior

As with the SDKv2-based resource, it parses `threshold[0].value` as 0.01

### Actual Behavior

```
       Error: Provider produced invalid plan
        
        Provider "registry.terraform.io/hashicorp/honeycombio" planned an invalid
        value for honeycombio_trigger.test.threshold[0].value: planned value
        cty.NumberFloatVal(0.01) does not match config value
        cty.MustParseNumberVal("0.010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003").
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
```

### Steps to Reproduce

`terraform plan`

Test to reproduce is on this branch: https://github.com/honeycombio/terraform-provider-honeycombio/commit/467e603fdc05ebb2879a1c62c1315a4a04cba8ed

### References

Reported bug: https://github.com/honeycombio/terraform-provider-honeycombio/issues/335

**Comment by bflad** [comment]
Hi @jharley 👋 Thank you for reporting this and sorry you are running into this unexpected situation here. The team is looking into this and we will try to provide an update soon.

**Comment by bflad** [comment]
Can you also confirm your Terraform CLI version? From the debug logs I see:

```
Adding potential Terraform CLI source of releases.hashicorp.com exact version "1.0.11" for installation
```

But if you could confirm that, that would be great. It would also be helpful to try it out on the latest version (1.5.4 as of this writing), if it does happen to be that older version, just to confirm whether this is a bug that has resolved in Terraform itself.

**Comment by bflad** [comment]
Terraform's number handling is arbitrary precision, meaning that the framework itself must preserve that precision when roundtripping a number value. The fix here will likely be a patch release of the terraform-plugin-framework Go module where the internals of the Float64 value storage will be switched from the `float64` type to the `*big.Float` type to match that implementation detail. The existing functions for getting/setting values should remain the same though.

**Comment by austinvalle** [comment]
Hi there @jharley 👋🏻 , we've released a fix for this bug in `terraform-plugin-framework v1.3.4`. 

One note is that Plugin SDKv2 has [legacy data consistency handling](https://github.com/hashicorp/terraform-plugin-sdk/issues/1227) which would allow the following config to be stored in state as `0.01`:
```terraform
resource “examplecloud_resource” “test” {
   float64_attribute = 1 - 0.99
}
```

When you migrate a resource like this to Plugin Framework, the prior value of `0.01` will be preserved in state. If you were to delete/recreate this resource, the value stored in state will be exactly what is in config, `0.010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003`.

Providers are allowed to store config exactly or store prior state exactly, so either of these situations are valid 👍🏻
