### ISSUE TITLE
(Question) Adding `ConflictsWith` for Provider Block 

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-plugin-framework#838]
### Description

When working on migrating the `helm` provider to the plugin-framework, I noticed that theres no support for a `ConflictsWith` feature when configuring the provider. 

Is this due to the expectation that any provider configuration being done such as setting default values and also checking for conflicts should be done within the `Configure` function? I ask this due to the response from `DefaultValues`

https://github.com/hashicorp/terraform-plugin-framework/issues/539

### Use-cases

`ConfigPath` and `ConfigPaths` can conflict with one another within the provider configuration. This is a simple check within the provider configure function, although I want to open this issue for those that run into a similar situation where more Conflicts could arise when developing providers using the plugin-framework

**Comment by bflad** [comment]
Hi @BBBmau 👋 Thank you for raising this.

> Is this due to the expectation that any provider configuration being done such as setting default values and also checking for conflicts should be done within the `Configure` function?

That is one potential solution. Providers do not have a "planning" phase, only configuration validation and configuration calls from Terraform. More details about provider configuration validation can be found in the [framework website documentation](https://developer.hashicorp.com/terraform/plugin/framework/providers/validate-configuration).

> I noticed that theres no support for a `ConflictsWith` feature when configuring the provider.

The [terraform-plugin-framework-validators Go module](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework-validators) contains validators such as `ConflictsWith` for individual attributes in the schema definition or [`Conflicting` for provider configuration-level validation](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework-validators/providervalidator#Conflicting).

So for example:

```go
import (
  "github.com/hashicorp/terraform-plugin-framework-validators/providervalidator"
)

func (p ExampleProvider) ConfigValidators(ctx context.Context) []provider.ConfigValidator {
    return []provider.ConfigValidator{
        providervalidator.Conflicting(
            path.MatchRoot("config_path"),
            path.MatchRoot("config_paths"),
        ),
    }
}
```

Is this what you are looking for in this case?

**Comment by BBBmau** [comment]
This is what I was looking for, thank you! I saw that the docs provided this here, https://developer.hashicorp.com/terraform/plugin/framework/resources/validate-configuration

I'll do a more extensive search within the docs the next time around. Thank you for getting back to me!
