### ISSUE TITLE
ModifyPlan call for destroy plan operations

### ISSUE THREAD

**Issue by akinross** [hashicorp/terraform-plugin-framework#839]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.3.5
```

### Use-cases

I'm trying to use ModifyPlan function to set the to be send payload information (constructed and send during create/update/delete functions) in plan. This `payload` value in the plan output can then be used for further analysis by other tools. I am facing the issue that ModifyPlan does not seem to be executed for resources that are planned for destroy, and thus I am unable to change the plan value of `payload` for to be destroyed resources. Is there a way to achieve this?

```
func (r *exampleResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	tflog.Trace(ctx, "start plan modification of resource: exampleResource")

	... code logic ...

	tflog.Trace(ctx, "end plan modification of resource: exampleResource")
} 
```

**Comment by akinross** [comment]
HI @austinvalle, 

I am using Terraform v1.2.2 so that would explain why it is not being triggered.

I had a look at private state, but not sure how that would help the use case that I am trying to solve, which is outputting that `payload` attribute during a plan for a destroy operation of the resource. Per my understanding the Delete function would get called on the actual destroy operation of the resource, in which I already have access to a function that constructs this payload from the known attributes. Only option for this I would then see is to expose the payload for destroy in a separate computed schema attribute, then it would be shown in output. Then logic would be bit more complex for retrieving the information from plan but I think this should be possible.

Thanks for the response, if you have no further comments the issue could be closed.

**Comment by austinvalle** [comment]
Oh I apologize, I missed that portion of your use-case that you're looking to **output** the information as a part of the destroy plan.

Terraform won't allow any non-null values for a resource's destroy plan anyways, so the only real option you'd have for plan output would be the computed attribute like you mentioned. The output could be confusing for practitioners as the plan will always show:
```bash
<payload_value> -> null
```
