### ISSUE TITLE
CustomizeDiff functionality in framework

### ISSUE THREAD

**Issue by JakeNeyer** [hashicorp/terraform-plugin-framework#859]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.4.1
```

### Use-cases

Perhaps this functionality already exists in the new framework under a different pattern. In which case, maybe all that is needed is a link to some documentation. 

I'm currently working with an api (for better or worse) that will return masked values given a clear text value. For example, given `api_key: foobar` the response will contain `api_key: ******`.  This lends issues when applying due to state inconsistencies as the framework returns something along the lines of `.configuration.api_key: was cty.StringVal("foobar"), but now cty.StringVal("******").` I see that sdkv2 had the ability to handle such cases by [customizing diffs](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/customizing-differences). It would be useful if similar functional was exposed in the new framework.

### Attempted Solutions

I attempted to completely omit the response values from state which _kind of_ works. One of the consequences of doing so means that imports will be `updated in-place ` on the next apply.

### Proposal

Expose the ability to ignore inconsistent state on the `schema.Attribute` interface. Maybe this could surface as an option like `Computed`, `Required`, etc.  (`IgnoreInconsistent`) or perhaps this functionality acts more closely to the `CustomizeDiff` functionality where it's a function attached to `schema.Attribute` similar to the planmodifiers.

### References

N/A

**Comment by bendbennett** [comment]
Hi @JakeNeyer 👋 

Sorry you ran into trouble here. There is information in the documentation relating to migrating a [Terraform provider from SDKv2 to the plugin Framework](https://developer.hashicorp.com/terraform/plugin/framework/migrating), that covers switching from using a `CustomizeDiff` in SDKv2 to using [Plan Modification](https://developer.hashicorp.com/terraform/plugin/framework/migrating/resources/plan-modification) in the Framework. Hopefully this will prove useful. If you have specific questions could I ask you to create a new topic on the [Terraform Providers Discuss Forum](https://discuss.hashicorp.com/c/terraform-providers/31), providing as much detail as is needed to reproduce any issues that you are running into. Thanks!

I'm going to close this as it doesn't seem that there is an issue with the Framework at this point.

**Comment by JakeNeyer** [comment]
This is super helpful. Thanks kindly, @bendbennett!
