### ISSUE TITLE
Make registry publishing easier

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-framework#87]
### Module version

```
v0.2.0
```

### Use-cases

Releasing a provider built with the framework involves including a manifest in your release assets to specify the protocol versions to advertise. SDKv2 providers _can_ use this manifest, but don't _need_ to since the registry defaults to protocol 5, which is the right choice for most SDKv2 providers.

### Proposal

To make it easier to get started with releasing framework providers, I'm suggesting we do one of the following:

* Build and publish a GitHub action that will run provider releases.
* Add the manifest to our current GoReleaser-based releases.

Publishing a GitHub action is a heavy lift and comes with maintenance burden, but gives us more control over the provider release process we're pointing users towards.

Adding the manifest to oru current GoReleaser-based releases is tricky, as GoReleaser doesn't support including arbitary files in the release. So we'd need to petition the GoReleaser team to add support for that.

We could take a third, middle ground where we use GoReleaser for the parts of our release process it supports, and write an Action for the parts it doesn't. We would need to move the SHASUM generation and signing out of GoReleaser and into the action, though, as the manifest needs to included in that signed SHASUM file.

Whichever route we choose, I propose we update terraform-provider-scaffolding with it and include a `manifest.json` in it that advertises support for protocol 5. Whenever terraform-provider-scaffolding is updated to use the framework, at that point we should update the manifest to advertise support for protocol 6.

**Comment by anGie44** [comment]
Hi @paddycarver just an observation regarding this line:
> Adding the manifest to our current GoReleaser-based releases is tricky, as GoReleaser doesn't support including arbitary files in the release. So we'd need to petition the GoReleaser team to add support for that.

I noticed in the release documentation https://goreleaser.com/customization/release/ , there's an `extra_files` parameter that might be the support needed to add the manifest file to the release if that's the approach chosen..only thing i'm not sure of then, is if that file gets included in the SHA2356SUMS file generated by GoReleaser 🤔

**Comment by paddycarver** [comment]
Yeah, I saw that after writing the issue up, but it still doesn't solve the problem, because it's not included in the SHA256SUMS file (goreleaser/goreleaser#1898), and would need the file to be renamed on every release. Ideally, you could just have a `manifest.json` in the root of the repo, and the release process would give it the appropriate expanded name (`terraform-provider-name_version_manifest.json`) in the release, so no file renaming needs to be done manually.

**Comment by anGie44** [comment]
Thanks for posting the above @bflad ! I was wondering for a while how to get around the `goreleaser` releaser error after creating the new versioned manifest file

**Comment by bflad** [comment]
This upstream improvement should further simplify the new manifest file handling so the versioned naming is native within `goreleaser` instead of extra steps outside of it: https://github.com/goreleaser/goreleaser/issues/2656

**Comment by bflad** [comment]
`goreleaser` can now automatically remap file names natively during the checksum and release pipes. For context, in my test provider, I have a statically named `terraform-registry-manifest.json` file that now gets the versioned naming during release.

Verified via:

- https://github.com/bflad/ghaction-terraform-provider-release/blob/main/.github/workflows/community.yml
- https://github.com/bflad/terraform-provider-framework/compare/v0.1.2...v0.1.3
- https://github.com/bflad/terraform-provider-framework/releases/tag/v0.1.3
- https://registry.terraform.io/providers/bflad/framework/0.1.3

**Comment by bflad** [comment]
Redirects are in place and now https://www.terraform.io/docs/registry/providers/publishing.html has the canonical information for both SDKv2 and this framework. 👍
