### ISSUE TITLE
Building List Nested Attributes Paths

### ISSUE THREAD

**Issue by albertored** [hashicorp/terraform-plugin-framework#888]
I'm following the official [guide](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/paths#building-list-nested-attributes-paths) to add an attribute error from a custom `ValidateConfig` method on my resource. The resoruce beside other things as an attribute that represents a list of JSON patches and I need to ensure that some of the underlying attributes are set or not based on the operation type.

The problem I have is that adding an error with the path `path.Root("json_patches").AtListIndex(0).AtName("from")` returns the wrong line in the report pointing to the whole resource instead of the particular attribute. 

### Module version
```
github.com/hashicorp/terraform-plugin-framework v1.4.2
```

### Relevant provider source code

```go

var (
	_ resource.Resource                   = &myResource{}
	_ resource.ResourceWithValidateConfig = &myResource{}
)

func (r *myResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"json_patches": schema.ListNestedAttribute{
				Optional: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"operation": schema.StringAttribute{
							Required: true,
							Validators: []validator.String{
								stringvalidator.OneOf([]string{"add", "copy", "move", "remove", "replace"}...),
							},
						},
						"path": schema.StringAttribute{
							Required: true,
						},
						"value_json": schema.StringAttribute{
							Optional: true,
						},
						"from": schema.StringAttribute{
							Optional: true,
						},
					},
				}
			},
		},
	}
}

func (r *myResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data myResourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

       patch =  data.JsonPatches[0]
       resp.Diagnostics.AddAttributeError(
		path.Root("json_patches").AtListIndex(0).AtName("from"),
		"Conflicting Attribute Configuration",
		fmt.Sprintf("When patch operation is %s, %s must not be configured", patch.Operation.ValueString(), attrName),
	)
}
```

### Terraform Configuration Files
```hcl
resource "my_resource" "xxx" {
  json_patches = [
    {
      operation  = "add"
      path       = "/json/path"
      value_json = jsonencode([{ "foo" : "bar" }])
      from       = "from"
    }
  ]
}
```

### Expected Behavior

```
│ Error: Conflicting Attribute Configuration
│ 
│   with my_resource.xxx,
│   on main.tf line 7, in resource "my_resource" "xxx":
│   3:     {
│   4:       operation = "add"
│   5:       path      = "/json/path"
│   6:       value_json =  jsonencode([{ "foo" : "bar" }])
│   7:       from      = "from"
│   8:     }
│ 
│ When patch operation is add, from must not be configured
```

### Actual Behavior

```
│ Error: Conflicting Attribute Configuration
│ 
│   with my_resource.xxx,
│   on main.tf line 41, in resource "my_resource" "xxx":
│   1: resource "my_resource" "xxx" {
│ 
│ When patch operation is add, from must not be configured
```

**Comment by chrismarget** [comment]
I think your problem is the same as [Terraform #33491](https://github.com/hashicorp/terraform/issues/33491)

**Comment by bflad** [comment]
Thank you @chrismarget for posting that issue link -- I knew this sounded familiar. 😅 

Hi @albertored 👋 Thank you for this report. I believe you are running into the same issue mentioned in https://github.com/hashicorp/terraform/issues/33491, in which the provider side is sending Terraform the expected information correctly, however the configuration source bits in Terraform error message handling require a change. Since there is nothing to be done in this Go module, I'm going to close this issue, but please feel free to follow the Terraform issue for further updates on this.

**Comment by albertored** [comment]
Thank you!
