### ISSUE TITLE
incorrect handling of nil pointer receiver in `Diagnostics.Append`

### ISSUE THREAD

**Issue by john-behm-bertelsmann** [hashicorp/terraform-plugin-framework#932]
It's not possible to handle the case when the receiver is nil in line 47 which is then a nil pointer to a slice (pointer).
This line is not covered by tests, as it is incorrect and impossible to handle.
It gives a false sense of that such a case can be handled, which it cannot.

https://github.com/hashicorp/terraform-plugin-framework/blob/f35653eee5dbea1a5cbcd1f421f0ec6f614a4d87/diag/diagnostics.go#L37-L53

**Comment by bflad** [comment]
Hi @john-behm-bertelsmann 👋 Thank you for reporting this. Did you encounter this as an issue when writing provider code or are you reporting this as a potential gotcha that someone might run into?

**Comment by bflad** [comment]
Thank you for that additional context, @john-behm-bertelsmann! Would you like to submit the code fix for this?
