### ISSUE TITLE
Discuss and Implement Go Static Analysis Tooling

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-framework#96]
### Module version

```
v0.2.0
```

### Use-cases

The Go ecosystem has a plethora of static analysis tooling, which can help catch code bugs, enhance quality, and automate style decisions. For example, [`revive`](https://revive.run/) (the spiritual successor to `golint`) can require Go documentation comments on exported types and functions, which seems desirable given the purpose of this codebase.

### Proposal

I have worked successfully with [`golangci-lint`](https://golangci-lint.run/) via GitHub Actions (and before that `gometalinter`), which brings many static analysis tools under one tool and configuration. This is open for discussion though!

**Comment by paddycarver** [comment]
I could've sworn we were running `golangci-lint` on PRs and commits, but I appear to be mistaken. I'd be in favor of turning it on.
