### ISSUE TITLE
Computed only dynamic typed attribute tolerate type inconsistency

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform-plugin-framework#969]
### Module version

```
v1.7.0
```

### Use-cases

I'm trying to add the new support of dynamic type to the restful provider (a general provider for support restful APIs), in my [test branch](https://github.com/magodo/terraform-provider-restful/commit/59b0aa4a755c64da5ca5fc5becbad74138416fd0).

There is a major resource in this provider named [`restful_resource`](https://registry.terraform.io/providers/magodo/restful/latest/docs/resources/resource). The essential attribute is the `body`, which was a string represents the configurable attribute of this restful resource. Meanwhile it exports an attribute named `output` that by default holds the whole API model, which is also a string.

What I'm trying to do is to change the types of `body` and `output` from string to dynamic type. To support these well, the [type consistency](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/dynamic-data#understanding-type-consistency) needs to take into consideration for sure. For the `body`, it works well as the types of each attribute is defined by the user's TF config (though there are still works needed for import support, but I leave it as is off topic).

Whilst for `output`, since it is a comptued only attribute, we don't have the information of type. So in this case, what we can do is to imply the types of a JSON object by default. E.g. assume the json array as `tuple`, and json object as `object`. The problem of doing this is that when something changed in the remote end (comparing to the state), e.g. size change for a `tuple`, or new attribute added for an `object`, we will violate the type consistency issue, results into error like below:

> │ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to examplecloud_thing.example, provider "provider[\"TYPE\"]" produced an unexpected new value: .example_attribute: wrong final value type: tuple required.
│ 
│ This is a bug in the provider, which should be reported in the providers own issue tracker.

### Proposal

I'm not sure whether it is possible or introduce a side effect, but I'd like there is a way to allow computed only attribute to tolerate the type inconsistency issue above, so that we can manage to change the type of `output` to dynamic.

Meanwhile, if there is anything I missed during my implementation, it's also appreciated to point out.

**Comment by magodo** [comment]
It turns out that with the following change, the `output` can support the expected behavior: https://github.com/magodo/terraform-provider-restful/commit/055137eebca404f091b212b47733bcfca0295dd7

**Comment by austinvalle** [comment]
Hey there @magodo 👋🏻 , thanks for reporting this and sorry you're into trouble here.

This initially looks like a framework bug to me, because the computed dynamic value should be allowed to determine it's own type and value if not already planned.

Digging a little deeper with your example, it looks like the [automatic marking of computed values as unknown](https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification#plan-modification-process) the framework does seems to be including type information when marking a dynamic value as unknown, which needs to be fixed.

**Comment by austinvalle** [comment]
@magodo The fix has been merged to main and will be released with the upcoming `terraform-plugin-framework v1.8.0` release.

In the meantime, you can test your changes off the latest changes in `main` if you'd like:
```bash
go get -u github.com/hashicorp/terraform-plugin-framework@main
```
