### ISSUE TITLE
When applying changes to, provider produced an unexpected new value: .name: was cty.StringVal("**"), but now null.

### ISSUE THREAD

**Issue by thulasirajkomminar** [hashicorp/terraform-plugin-framework#979]
### Module version

```
v1.7.0
```

### Relevant provider source code

```go
"name": schema.StringAttribute{
	Computed:    true,
	Optional:    true,
	Description: "The name of the resource.",
	PlanModifiers: []planmodifier.String{
		stringplanmodifier.UseStateForUnknown(),
	},
},
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

In the HCL config I set the name but the api does not return the name back so since I used the `UseStateForUnknown` plan modifier I expected the framework will populate the config value to the state but I get an error.
### Actual Behavior

`When applying changes to, provider produced an unexpected new value: .name: was cty.StringVal("**"), but now null.`

**Comment by thulasirajkomminar** [comment]
This is being discussed here https://discuss.hashicorp.com/t/when-applying-changes-to-provider-produced-an-unexpected-new-value-name-was-cty-stringval-but-now-null/65159

**Comment by bendbennett** [comment]
Hi @thulasirajkomminar 👋 

As this issue does not appear to be a bug and there is a thread on [Discuss](https://discuss.hashicorp.com/t/when-applying-changes-to-provider-produced-an-unexpected-new-value-name-was-cty-stringval-but-now-null/65159) for this topic, I'm going to close this issue out.
